/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/**
 * Pre-compiled 5-locale Google Admin console header and value normalization catalog (en, ja, ko, zh-CN, id).
 */

var CERA_CONSOLE_LABELS = {
  "columns": {
    "acara": "event",
    "akun yang digunakan untuk login ke aplikasi web": "web app signed-in account",
    "akun yang digunakan untuk login ke aplikasi web sumber": "source web app signed-in account",
    "alasan peristiwa": "event reason",
    "class tools config change": "class tools config change",
    "command line flags": "command line flags",
    "command line switches": "command line switches",
    "command-line flags": "command line flags",
    "content name": "content name",
    "content size": "content size",
    "content transfer method": "content transfer method",
    "content type": "content type",
    "date": "date",
    "destination": "destination",
    "detector id": "detector id",
    "detector name": "detector name",
    "device name": "device name",
    "device user": "device user",
    "domain": "domain",
    "event": "event",
    "event reason": "event reason",
    "event result": "event result",
    "fasilitas": "resource",
    "hasil peristiwa": "event result",
    "id aturan yang dipicu": "triggered rule name",
    "id pendeteksi": "detector id",
    "jenis konten": "content type",
    "jenis pemicu": "trigger type",
    "kategori url": "url category",
    "latensi pemindaian server": "server scan latency",
    "metode transfer konten": "content transfer method",
    "nama aturan yang dipicu": "triggered rule name",
    "nama detektor": "detector name",
    "nama konten": "content name",
    "nama pendeteksi": "detector name",
    "nama perangkat": "device name",
    "nama unit organisasi": "organizational unit name",
    "organisational unit": "organizational unit",
    "organisational unit name": "organizational unit name",
    "organizational unit": "organizational unit",
    "organizational unit name": "organizational unit name",
    "pengguna": "user",
    "pengguna perangkat": "device user",
    "pengguna profil": "profile user",
    "pengguna yang memicu": "trigger user",
    "peristiwa": "event",
    "perubahan konfigurasi alat kelas": "class tools config change",
    "profile user": "profile user",
    "resource": "resource",
    "resources": "resource",
    "server scan latency": "server scan latency",
    "server scan status": "server scan status",
    "source": "source",
    "source web app signed-in account": "source web app signed-in account",
    "status pemindaian server": "server scan status",
    "sumber": "source",
    "sumber daya": "resource",
    "tab url": "tab url",
    "tanda command line": "command line flags",
    "tanggal": "date",
    "trigger type": "trigger type",
    "trigger user": "trigger user",
    "triggered rule id": "triggered rule name",
    "triggered rule ids": "triggered rule name",
    "triggered rule name": "triggered rule name",
    "triggered rules": "triggered rules",
    "tujuan": "destination",
    "ukuran konten": "content size",
    "unit organisasi": "organizational unit",
    "url": "url",
    "url category": "url category",
    "url tab": "tab url",
    "url のカテゴリ": "url category",
    "url カテゴリ": "url category",
    "url 카테고리": "url category",
    "web app signed-in account": "web app signed-in account",
    "イベント": "event",
    "イベントの理由": "event reason",
    "イベントの発生理由": "event reason",
    "イベントの結果": "event result",
    "イベント結果": "event result",
    "ウェブアプリにログインしているアカウント": "web app signed-in account",
    "ウェブアプリのログイン アカウント": "web app signed-in account",
    "クラスツールの設定変更": "class tools config change",
    "コマンドライン フラグ": "command line flags",
    "コンテンツ タイプ": "content type",
    "コンテンツのサイズ": "content size",
    "コンテンツの転送方法": "content transfer method",
    "コンテンツ名": "content name",
    "サーバー スキャンのステータス": "server scan status",
    "サーバー スキャンのレイテンシ": "server scan latency",
    "ソース": "source",
    "ソースのウェブアプリにログインしているアカウント": "source web app signed-in account",
    "ソースのウェブアプリのログイン アカウント": "source web app signed-in account",
    "タブの url": "tab url",
    "デバイス ユーザー": "device user",
    "デバイスのユーザー": "device user",
    "デバイス名": "device name",
    "トリガーされたルール": "triggered rules",
    "トリガーされたルール名": "triggered rule name",
    "トリガーしたユーザー": "trigger user",
    "トリガーのタイプ": "trigger type",
    "ドメイン": "domain",
    "プロファイル ユーザー": "profile user",
    "プロファイルのユーザー": "profile user",
    "ユーザー": "user",
    "リソース": "resource",
    "个人资料用户": "profile user",
    "事件": "event",
    "事件原因": "event reason",
    "事件结果": "event result",
    "内容名称": "content name",
    "内容大小": "content size",
    "内容类型": "content type",
    "内容转移方法": "content transfer method",
    "命令行 flag": "command line flags",
    "域名": "domain",
    "已登录 web 应用的账号": "web app signed-in account",
    "已登录源 web 应用的账号": "source web app signed-in account",
    "日付": "date",
    "日期": "date",
    "服务器扫描延迟时间": "server scan latency",
    "服务器扫描状态": "server scan status",
    "来源": "source",
    "标签页网址": "tab url",
    "检测器 id": "detector id",
    "检测器名称": "detector name",
    "検出機能 id": "detector id",
    "検出機能のカテゴリ": "detector category",
    "検出機能名": "detector name",
    "検出項目 id": "detector id",
    "検出項目の名前": "detector name",
    "用户": "user",
    "目标位置": "destination",
    "移行先": "destination",
    "組織部門": "organizational unit",
    "組織部門の名前": "organizational unit name",
    "組織部門名": "organizational unit name",
    "组织部门": "organizational unit",
    "组织部门名称": "organizational unit name",
    "网址": "url",
    "网址类别": "url category",
    "网域": "domain",
    "触发器类型": "trigger type",
    "触发的规则名称": "triggered rule name",
    "触发者": "trigger user",
    "设备名称": "device name",
    "设备用户": "device user",
    "课堂工具配置更改": "class tools config change",
    "资源": "resource",
    "送信先": "destination",
    "감지기 이름": "detector name",
    "검사 프로그램 id": "detector id",
    "검사 프로그램 이름": "detector name",
    "기기 사용자": "device user",
    "기기 이름": "device name",
    "날짜": "date",
    "대상": "destination",
    "도메인": "domain",
    "리소스": "resource",
    "명령줄 플래그": "command line flags",
    "사용자": "user",
    "서버 스캔 상태": "server scan status",
    "서버 스캔 지연 시간": "server scan latency",
    "소스": "source",
    "소스 웹 앱 로그인 계정": "source web app signed-in account",
    "수업 도구 구성 변경": "class tools config change",
    "웹 앱 로그인 계정": "web app signed-in account",
    "이벤트": "event",
    "이벤트 결과": "event result",
    "이벤트 사유": "event reason",
    "이벤트 이유": "event reason",
    "조직 단위": "organizational unit",
    "조직 단위 이름": "organizational unit name",
    "콘텐츠 유형": "content type",
    "콘텐츠 이름": "content name",
    "콘텐츠 전송 방법": "content transfer method",
    "콘텐츠 크기": "content size",
    "탭 url": "tab url",
    "트리거 사용자": "trigger user",
    "트리거 유형": "trigger type",
    "트리거된 규칙 이름": "triggered rule name",
    "프로필 사용자": "profile user"
  },
  "events": {
    "akses data": "Data access",
    "browser crash": "Browser crash",
    "browser error": "Browser crash",
    "browser extension install": "Browser extension install",
    "browser extension modified": "Browser extension install",
    "browser launch with command line flags": "Browser launch",
    "browser launch with command-line flags": "Browser launch",
    "certificate": "Certificate",
    "content transfer": "Content transfer",
    "content unscanned": "Content unscanned",
    "data access": "Data access",
    "data access control": "Data access",
    "data sensitif ditransfer": "Sensitive data transfer",
    "ekstensi browser diubah": "Browser extension install",
    "extension request": "Extension request",
    "kebocoran sandi": "Password breach",
    "konten tidak dipindai": "Content unscanned",
    "kontrol akses data": "Data access",
    "kunjungan situs tidak aman": "Unsafe site visit",
    "kunjungan situs yang tidak aman": "Unsafe site visit",
    "login": "Login",
    "malware transfer": "Malware transfer",
    "password breach": "Password breach",
    "password changed": "Password changed",
    "password reuse": "Password reuse",
    "peluncuran browser dengan tanda command line": "Browser launch",
    "pemfilteran url": "URL filtering",
    "penggunaan ulang sandi": "Password reuse",
    "penginstalan ekstensi browser": "Browser extension install",
    "permintaan ekstensi": "Extension request",
    "print job": "Print job",
    "sandi diubah": "Password changed",
    "sensitive data transfer": "Sensitive data transfer",
    "sertifikat": "Certificate",
    "sinkronkan": "Sync",
    "suspicious url": "Suspicious URL",
    "sync": "Sync",
    "transfer data sensitif": "Sensitive data transfer",
    "transfer konten": "Content transfer",
    "transfer malware": "Malware transfer",
    "tugas pencetakan": "Print job",
    "unsafe site visit": "Unsafe site visit",
    "url filtering": "URL filtering",
    "url mencurigakan": "Suspicious URL",
    "url のフィルタリング": "URL filtering",
    "url 필터링": "URL filtering",
    "コマンドライン フラグを使用したブラウザの起動": "Browser launch",
    "コンテンツの転送": "Content transfer",
    "コンテンツ未スキャン": "Content unscanned",
    "センシティブ データの転送": "Sensitive data transfer",
    "データアクセス": "Data access",
    "データアクセス制御": "Data access",
    "パスワードの再利用": "Password reuse",
    "パスワードの変更": "Password changed",
    "パスワード漏洩": "Password breach",
    "ブラウザのクラッシュ": "Browser crash",
    "ブラウザの拡張機能が変更されました": "Browser extension install",
    "ブラウザ拡張機能のインストール": "Browser extension install",
    "マルウェアの転送": "Malware transfer",
    "ログイン": "Login",
    "不審な url": "Suspicious URL",
    "传输恶意软件": "Malware transfer",
    "内容传输": "Content transfer",
    "内容未经扫描": "Content unscanned",
    "内容转移": "Content transfer",
    "印刷ジョブ": "Print job",
    "危険なサイトへのアクセス": "Unsafe site visit",
    "可疑网址": "Suspicious URL",
    "同期": "Sync",
    "同步": "Sync",
    "安全でないサイトへのアクセス": "Unsafe site visit",
    "安装浏览器扩展程序": "Browser extension install",
    "密码盗用": "Password breach",
    "已修改浏览器扩展程序": "Browser extension install",
    "恶意软件传输": "Malware transfer",
    "打印任务": "Print job",
    "扩展程序请求": "Extension request",
    "拡張機能のリクエスト": "Extension request",
    "敏感数据传输": "Sensitive data transfer",
    "数据访问权限": "Data access",
    "数据访问权限控制": "Data access",
    "更改了密码": "Password changed",
    "機密データの転送": "Sensitive data transfer",
    "浏览器启动(带有命令行 flag)": "Browser launch",
    "浏览器崩溃": "Browser crash",
    "登录": "Login",
    "网址过滤": "URL filtering",
    "証明書": "Certificate",
    "访问不安全的网站": "Unsafe site visit",
    "证书": "Certificate",
    "重复使用密码": "Password reuse",
    "검사되지 않은 콘텐츠": "Content unscanned",
    "데이터 액세스": "Data access",
    "데이터 액세스 제어": "Data access",
    "동기화": "Sync",
    "로그인": "Login",
    "멀웨어 전송": "Malware transfer",
    "명령줄 플래그로 브라우저 실행": "Browser launch",
    "민감한 데이터 전송": "Sensitive data transfer",
    "민감한 정보 전송": "Sensitive data transfer",
    "브라우저 비정상 종료": "Browser crash",
    "브라우저 확장 프로그램 설치": "Browser extension install",
    "브라우저 확장 프로그램이 수정됨": "Browser extension install",
    "비밀번호 유출": "Password breach",
    "비밀번호 재사용": "Password reuse",
    "비밀번호가 변경됨": "Password changed",
    "안전하지 않은 사이트 방문": "Unsafe site visit",
    "의심스러운 url": "Suspicious URL",
    "인쇄 작업": "Print job",
    "인증서": "Certificate",
    "콘텐츠 전송": "Content transfer",
    "확장 프로그램 요청": "Extension request"
  },
  "triggerTypes": {
    "chromeos clipboard paste": "Clipboard copy",
    "chromeos printing": "Page print",
    "chromeos のクリップボードの貼り付け": "Clipboard copy",
    "chromeos の印刷": "Page print",
    "chromeos 剪贴板粘贴": "Clipboard copy",
    "chromeos 打印": "Page print",
    "chromeos 인쇄": "Page print",
    "chromeos 클립보드 붙여넣기": "Clipboard copy",
    "clipboard": "Clipboard",
    "clipboard copy": "Clipboard copy",
    "destination": "Destination",
    "download file": "File download",
    "file download": "File download",
    "file transfer": "File transfer",
    "file upload": "File upload",
    "page print": "Page print",
    "papan klip": "Clipboard",
    "pencetakan chromeos": "Page print",
    "pencetakan halaman": "Page print",
    "penempelan papan klip chromeos": "Clipboard copy",
    "salinan papan klip": "Clipboard copy",
    "tempel halaman": "Page paste",
    "tidak dikenal": "Unspecified",
    "tidak diketahui": "Unspecified",
    "tidak ditentukan": "Unspecified",
    "transfer file": "File transfer",
    "tujuan": "Destination",
    "unknown": "Unspecified",
    "unspecified": "Unspecified",
    "upload file": "File upload",
    "upload konten web": "Web content upload",
    "url visited": "URL visited",
    "url yang dikunjungi": "URL visited",
    "web content upload": "Web content upload",
    "アクセスした url": "URL visited",
    "ウェブ コンテンツのアップロード": "Web content upload",
    "クリップボード": "Clipboard",
    "クリップボードのコピー": "Clipboard copy",
    "クリップボードへのコピー": "Clipboard copy",
    "ファイル アップロード": "File upload",
    "ファイル ダウンロード": "File download",
    "ファイルのアップロード": "File upload",
    "ファイルのダウンロード": "File download",
    "ファイルの転送": "File transfer",
    "ファイル転送": "File transfer",
    "ページの印刷": "Page print",
    "ページの貼り付け": "Page paste",
    "ページ印刷": "Page print",
    "不明": "Unspecified",
    "剪贴板": "Clipboard",
    "剪贴板复制": "Clipboard copy",
    "打印页面": "Page print",
    "指定なし": "Unspecified",
    "文件上传": "File upload",
    "文件下载": "File download",
    "文件传输": "File transfer",
    "未指定": "Unspecified",
    "未知": "Unspecified",
    "目标位置": "Destination",
    "移行先": "Destination",
    "网页内容上传": "Web content upload",
    "访问的网址": "URL visited",
    "访问过的网址": "URL visited",
    "页面粘贴": "Page paste",
    "대상": "Destination",
    "방문한 url": "URL visited",
    "알 수 없음": "Unspecified",
    "웹 콘텐츠 업로드": "Web content upload",
    "지정되지 않음": "Unspecified",
    "클립보드": "Clipboard",
    "클립보드 복사": "Clipboard copy",
    "파일 다운로드": "File download",
    "파일 업로드": "File upload",
    "파일 전송": "File transfer",
    "페이지 붙여넣기": "Page paste",
    "페이지 인쇄": "Page print"
  },
  "eventResults": {
    "allowed": "ALLOWED",
    "blocked": "BLOCKED",
    "bypassed": "BYPASSED",
    "cancelled by user": "CANCELLED_BY_USER",
    "data masked": "DATA_MASKED",
    "data unmasked": "DATA_UNMASKED",
    "data yang disamarkan": "DATA_MASKED",
    "data yang tidak disamarkan": "DATA_UNMASKED",
    "detected": "DETECTED",
    "diabaikan": "BYPASSED",
    "dibatalkan oleh pengguna": "CANCELLED_BY_USER",
    "diblokir": "BLOCKED",
    "diinstal otomatis": "FORCE_INSTALLED",
    "diizinkan": "ALLOWED",
    "dikarantina": "QUARANTINED",
    "dilaporkan": "REPORTED",
    "diperingatkan": "WARNED",
    "diterapkan": "ENFORCED",
    "enforced": "ENFORCED",
    "force installed": "FORCE_INSTALLED",
    "force-installed": "FORCE_INSTALLED",
    "forced save to cloud": "FORCED_SAVE_TO_CLOUD",
    "quarantined": "QUARANTINED",
    "reported": "REPORTED",
    "simpan paksa ke cloud": "FORCED_SAVE_TO_CLOUD",
    "terdeteksi": "DETECTED",
    "tidak dikenal": "",
    "tidak diketahui": "",
    "tidak ditentukan": "",
    "unknown": "",
    "unspecified": "",
    "warned": "WARNED",
    "クラウドへの強制保存": "FORCED_SAVE_TO_CLOUD",
    "データがマスクされました": "DATA_MASKED",
    "データのマスクが解除されました": "DATA_UNMASKED",
    "ブロック": "BLOCKED",
    "ブロック中": "BLOCKED",
    "ブロック済み": "BLOCKED",
    "ユーザーによりキャンセル": "CANCELLED_BY_USER",
    "ユーザーによるキャンセル": "CANCELLED_BY_USER",
    "不明": "",
    "回避": "BYPASSED",
    "回避済み": "BYPASSED",
    "報告済み": "REPORTED",
    "已允许": "ALLOWED",
    "已取消遮盖数据": "DATA_UNMASKED",
    "已屏蔽": "BLOCKED",
    "已强制执行": "ENFORCED",
    "已报告": "REPORTED",
    "已检测到": "DETECTED",
    "已绕过": "BYPASSED",
    "已被用户取消": "CANCELLED_BY_USER",
    "已警告": "WARNED",
    "已遮盖数据": "DATA_MASKED",
    "已阻止": "BLOCKED",
    "已隔离": "QUARANTINED",
    "强制保存到云端": "FORCED_SAVE_TO_CLOUD",
    "强制安装": "FORCE_INSTALLED",
    "指定なし": "",
    "未指定": "",
    "未知": "",
    "検出済み": "DETECTED",
    "検疫済み": "QUARANTINED",
    "自動インストール": "FORCE_INSTALLED",
    "許可": "ALLOWED",
    "許可済み": "ALLOWED",
    "警告": "WARNED",
    "警告済み": "WARNED",
    "適用済み": "ENFORCED",
    "감지됨": "DETECTED",
    "강제 설치": "FORCE_INSTALLED",
    "경고됨": "WARNED",
    "데이터가 마스크 해제됨": "DATA_UNMASKED",
    "데이터가 마스크됨": "DATA_MASKED",
    "보고됨": "REPORTED",
    "사용자가 취소함": "CANCELLED_BY_USER",
    "스팸으로 분류됨": "QUARANTINED",
    "시행됨": "ENFORCED",
    "알 수 없음": "",
    "우회됨": "BYPASSED",
    "차단됨": "BLOCKED",
    "클라우드에 강제 저장": "FORCED_SAVE_TO_CLOUD",
    "허용됨": "ALLOWED"
  },
  "categories": {
    "acara & agenda": "Events & Listings",
    "acara khusus": "Special Occasions",
    "accidents and disasters": "Accidents & Disasters",
    "accounting and auditing": "Accounting & Auditing",
    "advertising and marketing": "Advertising & Marketing",
    "advokasi & masalah sosial": "Social Issues & Advocacy",
    "aerospace and defence": "Aerospace & Defense",
    "affiliate programmes": "Affiliate Programs",
    "agama & kepercayaan": "Religion & Belief",
    "ageing and geriatrics": "Aging & Geriatrics",
    "agregasi feed & bookmark sosial": "Social Bookmarking",
    "agriculture and forestry": "Agriculture & Forestry",
    "agrikultur & kehutanan": "Agriculture & Forestry",
    "ai generatif": "Generative AI",
    "aktivitas & game berorientasi keluarga": "Family-Oriented Games & Activities",
    "aktivitas air": "Water Activities",
    "akuntansi & pengauditan": "Accounting & Auditing",
    "alternative and natural medicine": "Alternative & Natural Medicine",
    "anak-anak & remaja": "Kids & Teens",
    "animal products and services": "Animal Products & Services",
    "antiques and collectibles": "Antiques & Collectibles",
    "aplikasi web & alat online": "Web Apps & Online Tools",
    "apple news": "News",
    "arcade and coin-op games": "Arcade & Coin-Op Games",
    "arts and entertainment": "Arts & Entertainment",
    "asosiasi profesi & keahlian": "Professional & Trade Associations",
    "astronomi": "Astronomy",
    "asuransi": "Insurance",
    "autos and vehicles": "Autos & Vehicles",
    "barang antik & barang koleksi": "Antiques & Collectibles",
    "barang elektronik konsumen": "Consumer Electronics",
    "barang mewah": "Luxury Goods",
    "beauty and fitness": "Beauty & Fitness",
    "beauty services and spas": "Beauty Services & Spas",
    "bed and bath": "Bed & Bath",
    "belanja": "Shopping",
    "belanja alami & ramah lingkungan": "Green & Eco-Friendly Shopping",
    "belanja kendaraan": "Vehicle Shopping",
    "berbagi foto & video": "Photo & Video Sharing",
    "berinvestasi": "Investing",
    "berita": "News",
    "berita bisnis": "Business News",
    "berita dunia": "World News",
    "berita gosip & tabloid": "Gossip & Tabloid News",
    "berita kesehatan": "Health News",
    "berita lokal": "Local News",
    "berita olahraga": "Sports News",
    "berita selebritas & hiburan": "Celebrities & Entertainment News",
    "berita siaran & jaringan": "Broadcast & Network News",
    "berita teknologi": "Technology News",
    "bicycles and accessories": "Bicycles & Accessories",
    "bisnis & industri": "Business & Industrial",
    "bisnis kecil": "Small Business",
    "blogging resources & services": "Blogging",
    "blogging resources and services": "Blogging",
    "boats and watercraft": "Boats & Watercraft",
    "books and literature": "Books & Literature",
    "broadcast and network news": "Broadcast & Network News",
    "buku & literatur": "Books & Literature",
    "buku audio": "Audiobooks",
    "business and industrial": "Business & Industrial",
    "business and productivity software": "Business & Productivity Software",
    "campers and rvs": "Campers & RVs",
    "celebrities and entertainment news": "Celebrities & Entertainment News",
    "chat suara & video chat": "Voice & Video Chat",
    "children and teens": "Kids & Teens",
    "clothing": "Apparel",
    "cloud storage": "Cloud Storage",
    "clubs and organisations": "Clubs & Organizations",
    "collaboration & conferencing software": "Collaboration & Conferencing",
    "collaboration and conferencing software": "Collaboration & Conferencing",
    "comics and animation": "Comics & Animation",
    "computer and video games": "Computer & Video Games",
    "construction and maintenance": "Construction & Maintenance",
    "cooking and recipes": "Cooking & Recipes",
    "cosmetology and beauty professionals": "Cosmetology & Beauty Professionals",
    "credit and lending": "Credit & Lending",
    "crowdfunding": "Crowdfunding",
    "cuaca": "Weather",
    "customised and performance vehicles": "Custom & Performance Vehicles",
    "dapur & ruang makan": "Kitchen & Dining",
    "dating and personals": "Dating & Personals",
    "death and tragedy": "Death & Tragedy",
    "dekorasi rumah & interior": "Home & Interior Decor",
    "deliveries and logistics": "Shipping & Logistics",
    "desain & pengembangan web": "Web Design & Development",
    "dewasa": "Adult",
    "directories and listings": "Directories & Listings",
    "direktori & listingan": "Directories & Listings",
    "disabled and special needs": "Disabled & Special Needs",
    "discount and outlet shops": "Discount & Outlet Stores",
    "dunia maya": "Virtual Worlds",
    "e-book": "E-Books",
    "ebook": "E-Books",
    "ecology and environment": "Ecology & Environment",
    "ekologi & lingkungan": "Ecology & Environment",
    "electronics and electrical": "Electronics & Electrical",
    "elektronik & listrik": "Electronics & Electrical",
    "email": "Email",
    "email & pesan": "Email & Messaging",
    "email and messaging": "Email & Messaging",
    "energi & utilitas": "Energy & Utilities",
    "energy and utilities": "Energy & Utilities",
    "engineering and technology": "Engineering & Technology",
    "ethnic and identity groups": "Ethnic & Identity Groups",
    "events and listings": "Events & Listings",
    "face and body care": "Face & Body Care",
    "family and relationships": "Family & Relationships",
    "family-orientated games and activities": "Family-Oriented Games & Activities",
    "farmasi": "Pharmacy",
    "farmasi & bioteknologi": "Pharmaceuticals & Biotech",
    "fashion and style": "Fashion & Style",
    "fasilitas & layanan medis": "Medical Facilities & Services",
    "feed aggregation & social bookmarking": "Social Bookmarking",
    "feed aggregation and social bookmarking": "Social Bookmarking",
    "feed 聚合与社交书签": "Social Bookmarking",
    "fiksi penggemar": "Fan Fiction",
    "file sharing and hosting": "File Sharing & Hosting",
    "film": "Movies",
    "financial planning and management": "Financial Planning & Management",
    "firearms and weapons": "Firearms & Weapons",
    "fisika": "Physics",
    "food and drink": "Food & Drink",
    "food and grocery delivery": "Food & Grocery Delivery",
    "food and grocery retailers": "Food & Grocery Retailers",
    "forum and chat providers": "Forum & Chat Providers",
    "freeware and shareware": "Freeware & Shareware",
    "fun and trivia": "Fun & Trivia",
    "game": "Games",
    "game arcade & koin": "Arcade & Coin-Op Games",
    "game balok": "Tile Games",
    "game dadu": "Dice Games",
    "game edukasi": "Educational Games",
    "game kartu": "Card Games",
    "game komputer & video game": "Computer & Video Games",
    "game meja": "Table Games",
    "game peran": "Roleplaying Games",
    "game pesta": "Party Games",
    "gifts and special event items": "Gifts & Special Event Items",
    "giveaway promosi & undian": "Sweepstakes & Promotional Giveaways",
    "gizi": "Nutrition",
    "gossip and tabloid news": "Gossip & Tabloid News",
    "grants, scholarships and financial aid": "Grants, Scholarships & Financial Aid",
    "green and eco-friendly shopping": "Green & Eco-Friendly Shopping",
    "grosir & likuidator": "Wholesalers & Liquidators",
    "hacking and cracking": "Hacking & Cracking",
    "hadiah & item momen khusus": "Gifts & Special Event Items",
    "hardware komputer": "Computer Hardware",
    "health education and medical training": "Health Education & Medical Training",
    "health foundations and medical research": "Health Foundations & Medical Research",
    "hewan peliharaan": "Pets",
    "hewan peliharaan & binatang": "Pets & Animals",
    "hibah, beasiswa & bantuan keuangan": "Grants, Scholarships & Financial Aid",
    "hiburan & info santai": "Fun & Trivia",
    "hobbies and leisure": "Hobbies & Leisure",
    "hobi & rekreasi": "Hobbies & Leisure",
    "home and interior design": "Home & Interior Decor",
    "home safety and security": "Home Safety & Security",
    "home storage and shelving": "Home Storage & Shelving",
    "home swimming pools, saunas & spas": "Swimming Pools, Saunas & Spas",
    "home swimming pools, saunas and spas": "Swimming Pools, Saunas & Spas",
    "hosting & berbagi file": "File Sharing & Hosting",
    "hosting web & pendaftaran domain": "Web Hosting & Domain Registration",
    "hotel & akomodasi": "Hotels & Accommodations",
    "hotels and accommodation": "Hotels & Accommodations",
    "house and garden": "Home & Garden",
    "hukum": "Legal",
    "hukum & pemerintah": "Law & Government",
    "humaniora": "Humanities",
    "humor": "Humor",
    "humour": "Humor",
    "hvac & kontrol suhu udara": "HVAC & Climate Control",
    "hvac and climate control": "HVAC & Climate Control",
    "iklan": "Classifieds",
    "ilmiah": "Science",
    "ilmu biologi": "Biological Sciences",
    "ilmu bumi": "Earth Sciences",
    "ilmu komputer": "Computer Science",
    "ilmu sosial": "Social Sciences",
    "industri hiburan": "Entertainment Industry",
    "industri jurnalisme & berita": "Journalism & News Industry",
    "industri kimiawi": "Chemicals Industry",
    "industri otomotif": "Automotive Industry",
    "industri pelayanan": "Hospitality Industry",
    "industrial materials and equipment": "Industrial Materials & Equipment",
    "instant messaging & sms": "Text & Instant Messaging",
    "institusi ilmiah": "Scientific Institutions",
    "internet & teknologi": "Internet & Technology",
    "internet and technology": "Internet & Technology",
    "jaringan": "Networking",
    "jaringan sosial": "Social Networks",
    "jobs and education": "Jobs & Education",
    "journalism and news industry": "Journalism & News Industry",
    "jurnal online & situs pribadi": "Online Journals & Personal Sites",
    "kamar tidur & kamar mandi": "Bed & Bath",
    "keamanan & keselamatan rumah": "Home Safety & Security",
    "keamanan komputer": "Computer Security",
    "keanehan": "Offbeat",
    "kebugaran": "Fitness",
    "kecantikan & kebugaran": "Beauty & Fitness",
    "kecelakaan & bencana": "Accidents & Disasters",
    "kehidupan liar": "Wildlife",
    "kekerasan & penyiksaan": "Violence & Abuse",
    "kelompok etnis & identitas": "Ethnic & Identity Groups",
    "keluarga & hubungan": "Family & Relationships",
    "kematian & tragedi": "Death & Tragedy",
    "kencan & pribadi": "Dating & Personals",
    "kendali hama": "Pest Control",
    "kendaraan bermotor": "Motor Vehicles",
    "kendaraan klasik": "Classic Vehicles",
    "kendaraan modifikasi & performa tinggi": "Custom & Performance Vehicles",
    "kendaraan niaga": "Commercial Vehicles",
    "kendaraan rekreasi (rv)": "Campers & RVs",
    "keperawatan": "Nursing",
    "kerajinan": "Crafts",
    "kesehatan": "Health",
    "kesehatan laki-laki": "Men's Health",
    "kesehatan masyarakat": "Public Health",
    "kesehatan mental": "Mental Health",
    "kesehatan perempuan": "Women's Health",
    "kesehatan reproduksi": "Reproductive Health",
    "keselamatan umum": "Public Safety",
    "keuangan": "Finance",
    "keuangan bisnis": "Business Finance",
    "kimia": "Chemistry",
    "kitchen and dining": "Kitchen & Dining",
    "klasik literatur": "Literary Classics",
    "klub & organisasi": "Clubs & Organizations",
    "kolam renang, sauna & spa untuk rumah": "Swimming Pools, Saunas & Spas",
    "komik & animasi": "Comics & Animation",
    "kompetisi olahraga internasional": "International Sports Competitions",
    "komunitas online": "Online Communities",
    "kondisi kesehatan": "Health Conditions",
    "konstruksi & pemeliharaan": "Construction & Maintenance",
    "kontes & penghargaan": "Merit Prizes & Contests",
    "kontes kecantikan": "Beauty Pageants",
    "kontrol radio & mainan model": "Radio Control & Modeling",
    "koper & aksesori perjalanan": "Luggage & Travel Accessories",
    "koran": "Newspapers",
    "kredit & pinjaman": "Credit & Lending",
    "lansia & pensiunan": "Seniors & Retirement",
    "law and government": "Law & Government",
    "layanan & agen perjalanan": "Travel Agencies & Services",
    "layanan & fasilitas blog": "Blogging",
    "layanan bisnis": "Business Services",
    "layanan foto & video": "Photo & Video Services",
    "layanan kecantikan & spa": "Beauty Services & Spas",
    "layanan real estate": "Real Estate Services",
    "layanan rumah tangga": "Domestic Services",
    "layanan sosial": "Social Services",
    "legal": "Legal",
    "lelang": "Auctions",
    "libraries and museums": "Libraries & Museums",
    "listingan real estat": "Real Estate Listings",
    "literatur & referensi medis": "Medical Literature & Resources",
    "literatur anak": "Children's Literature",
    "logam & pertambangan": "Metals & Mining",
    "luar ruangan": "Outdoors",
    "luggage and travel accessories": "Luggage & Travel Accessories",
    "magang": "Internships",
    "mainan": "Toys",
    "majalah": "Magazines",
    "makanan": "Food",
    "makanan & minuman": "Food & Drink",
    "manufaktur": "Manufacturing",
    "mass merchants and department stores": "Mass Merchants & Department Stores",
    "mata uang digital": "Digital Currencies",
    "matematika": "Mathematics",
    "media hiburan": "Entertainment Media",
    "media online": "Online Media",
    "medical devices and equipment": "Medical Devices & Equipment",
    "medical facilities and services": "Medical Facilities & Services",
    "medical literature and resources": "Medical Literature & Resources",
    "memasak & resep": "Cooking & Recipes",
    "merit prizes and contests": "Merit Prizes & Contests",
    "mesin telusur": "Search Engines",
    "metals and mining": "Metals & Mining",
    "militer": "Military",
    "minuman": "Beverages",
    "minuman beralkohol": "Alcoholic Beverages",
    "missing persons and abductions": "Missing Persons & Abductions",
    "mobile and wireless": "Mobile & Wireless",
    "mode & gaya": "Fashion & Style",
    "motivasi & bantuan mandiri": "Self-Help & Motivational",
    "music and audio": "Music & Audio",
    "musik & audio": "Music & Audio",
    "narkoba": "Recreational Drugs",
    "news": "News",
    "none": "Uncategorized",
    "obat alternatif & alami": "Alternative & Natural Medicine",
    "olahraga": "Sports",
    "olahraga air": "Water Sports",
    "olahraga bela diri": "Combat Sports",
    "olahraga ekstrem": "Extreme Sports",
    "olahraga fantasi": "Fantasy Sports",
    "olahraga hewan": "Animal Sports",
    "olahraga individu": "Individual Sports",
    "olahraga kampus": "College Sports",
    "olahraga motor": "Motor Sports",
    "olahraga musim dingin": "Winter Sports",
    "olahraga tim": "Team Sports",
    "online journals and personal sites": "Online Journals & Personal Sites",
    "open source": "Open Source",
    "operasi bisnis": "Business Operations",
    "oral and dental care": "Oral & Dental Care",
    "orang hilang & penculikan": "Missing Persons & Abductions",
    "otomotif & kendaraan": "Autos & Vehicles",
    "paediatrics": "Pediatrics",
    "paintball": "Paintball",
    "pakaian": "Apparel",
    "pameran kendaraan": "Vehicle Shows",
    "panduan & petunjuk perjalanan": "Travel Guides & Travelogues",
    "pasar barter & pasar luar ruangan": "Swap Meets & Outdoor Markets",
    "patio, halaman rumput & taman": "Patio, Lawn & Garden",
    "patio, lawn and garden": "Patio, Lawn & Garden",
    "pedagang grosir & pusat perbelanjaan": "Mass Merchants & Department Stores",
    "pediatri": "Pediatrics",
    "pekerjaan": "Jobs",
    "pekerjaan & pendidikan": "Jobs & Education",
    "pemasaran & pengoptimalan mesin telusur": "Search Engine Optimization",
    "pembinaan & pelatihan olahraga": "Sports Coaching & Training",
    "pemerintah": "Government",
    "pemerintahan": "Government",
    "pemrograman": "Programming",
    "penatu": "Laundry",
    "pendidikan": "Education",
    "pendidikan bisnis": "Business Education",
    "pendidikan kesehatan & pelatihan medis": "Health Education & Medical Training",
    "penerbangan rekreasi": "Recreational Aviation",
    "pengelolaan konten": "Content Management",
    "pengembangan properti": "Property Development",
    "pengiriman & logistik": "Shipping & Logistics",
    "penuaan & geriatri": "Aging & Geriatrics",
    "penurunan berat badan": "Weight Loss",
    "penyalahgunaan obat": "Substance Abuse",
    "penyandang disabilitas & kebutuhan khusus": "Disabled & Special Needs",
    "penyedia forum & chat": "Forum & Chat Providers",
    "penyedia layanan": "Service Providers",
    "penyimpanan & rak rumah": "Home Storage & Shelving",
    "penyimpanan cloud": "Cloud Storage",
    "people and society": "People & Society",
    "perabot rumah tangga": "Home Appliances",
    "perabotan rumah": "Home Furnishings",
    "perahu & kendaraan air": "Boats & Watercraft",
    "peralatan & material industri": "Industrial Materials & Equipment",
    "peralatan & perlengkapan medis": "Medical Devices & Equipment",
    "peralatan komunikasi": "Communications Equipment",
    "peralatan sains": "Scientific Equipment",
    "perang & konflik": "War & Conflict",
    "peraturan kendaraan & hukum berkendara": "Vehicle Codes & Driving Laws",
    "perawatan mata": "Vision Care",
    "perawatan mulut & gigi": "Oral & Dental Care",
    "perawatan rambut": "Hair Care",
    "perawatan wajah & tubuh": "Face & Body Care",
    "perbankan": "Banking",
    "percetakan & penerbitan": "Printing & Publishing",
    "perdagangan ritel": "Retail Trade",
    "perencanaan & pengelolaan keuangan": "Financial Planning & Management",
    "peretasan & cracking": "Hacking & Cracking",
    "periklanan & pemasaran": "Advertising & Marketing",
    "perjalanan & transportasi": "Travel & Transportation",
    "perjalanan khusus": "Specialty Travel",
    "perjudian": "Gambling",
    "perlengkapan & pakaian penggemar olahraga": "Sports Fan Gear & Apparel",
    "perlengkapan olahraga": "Sporting Goods",
    "perlengkapan rumah tangga": "Household Supplies",
    "permainan kata": "Word Games",
    "permainan papan": "Board Games",
    "pernak-pernik online": "Online Goodies",
    "perpustakaan & museum": "Libraries & Museums",
    "pesan-antar makanan & bahan makanan": "Food & Grocery Delivery",
    "pesawat pribadi": "Personal Aircraft",
    "pets and animals": "Pets & Animals",
    "pharmaceuticals and biotech": "Pharmaceuticals & Biotech",
    "photo and video services": "Photo & Video Services",
    "photo and video sharing": "Photo & Video Sharing",
    "politik": "Politics",
    "portal belanja": "Shopping Portals",
    "portal web": "Web Portals",
    "printing and publishing": "Printing & Publishing",
    "produk & layanan hewan": "Animal Products & Services",
    "produk tembakau & rokok elektrik": "Tobacco & Vaping Products",
    "profesional kosmetologi & kecantikan": "Cosmetology & Beauty Professionals",
    "professional and trade associations": "Professional & Trade Associations",
    "program afiliasi": "Affiliate Programs",
    "properti": "Real Estate",
    "property": "Real Estate",
    "property listings": "Real Estate Listings",
    "property services": "Real Estate Services",
    "proxy & filter": "Proxying & Filtering",
    "proxying and filtering": "Proxying & Filtering",
    "puisi": "Poetry",
    "puzzles and brain teasers": "Puzzles & Brainteasers",
    "radio control and modelling": "Radio Control & Modeling",
    "referensi": "Reference",
    "referensi bahasa": "Language Resources",
    "referensi geografis": "Geographic Reference",
    "referensi konsumen": "Consumer Resources",
    "referensi penulis": "Writers Resources",
    "referensi teknis": "Technical Reference",
    "referensi umum": "General Reference",
    "religion and belief": "Religion & Belief",
    "renovasi rumah": "Home Improvement",
    "restoran": "Restaurants",
    "retailer makanan & bahan makanan": "Food & Grocery Retailers",
    "ruang angkasa & pertahanan": "Aerospace & Defense",
    "rumah & kebun": "Home & Garden",
    "search engine optimisation and marketing": "Search Engine Optimization",
    "search engine optimization & marketing": "Search Engine Optimization",
    "self-help and motivational": "Self-Help & Motivational",
    "seluler & nirkabel": "Mobile & Wireless",
    "seni & desain visual": "Visual Art & Design",
    "seni & hiburan": "Arts & Entertainment",
    "seni pertunjukan": "Performing Arts",
    "seni rajah dan tindik": "Body Art",
    "seniors and retirement": "Seniors & Retirement",
    "senjata api & senjata": "Firearms & Weapons",
    "seo、sem": "Search Engine Optimization",
    "sepeda & aksesori": "Bicycles & Accessories",
    "skor & statistik olah raga": "Sport Scores & Statistics",
    "social issues and advocacy": "Social Issues & Advocacy",
    "software": "Software",
    "software bisnis & produktivitas": "Business & Productivity Software",
    "software gratis & shareware": "Freeware & Shareware",
    "software kolaborasi & konferensi": "Collaboration & Conferencing",
    "software pendidikan": "Educational Software",
    "spam elektronik": "Electronic Spam",
    "specialist travel": "Specialty Travel",
    "sport scores and statistics": "Sport Scores & Statistics",
    "sports coaching and training": "Sports Coaching & Training",
    "sports fan gear and clothing": "Sports Fan Gear & Apparel",
    "statistik & analisis web": "Web Stats & Analytics",
    "subcultures and niche interests": "Subcultures & Niche Interests",
    "subkultur & minat khusus": "Subcultures & Niche Interests",
    "suku cadang & servis kendaraan": "Vehicle Parts & Services",
    "swap meets and outdoor markets": "Swap Meets & Outdoor Markets",
    "sweepstakes and promotional giveaways": "Sweepstakes & Promotional Giveaways",
    "teka-teki & pengasah otak": "Puzzles & Brainteasers",
    "teknologi & rekayasa": "Engineering & Technology",
    "teknologi perusahaan": "Enterprise Technology",
    "tekstil & kain nontenun": "Textiles & Nonwovens",
    "telekonferensi": "Teleconferencing",
    "text and instant messaging": "Text & Instant Messaging",
    "textiles and non-wovens": "Textiles & Nonwovens",
    "tidak ada": "Uncategorized",
    "tidak dikategorikan": "Uncategorized",
    "tidak dikenal": "Uncategorized",
    "tidak diketahui": "Uncategorized",
    "tidak ditentukan": "Uncategorized",
    "tindakan menyakiti diri sendiri": "Self-Harm",
    "tobacco and vaping products": "Tobacco & Vaping Products",
    "toko buku eceran": "Book Retailers",
    "toko diskon & outlet": "Discount & Outlet Stores",
    "tokoh & masyarakat": "People & Society",
    "topik sensitif": "Sensitive Subjects",
    "transport": "Transportation",
    "transportasi": "Transportation",
    "travel agencies and services": "Travel Agencies & Services",
    "travel and transportation": "Travel & Transportation",
    "travel guides and travelogues": "Travel Guides & Travelogues",
    "tujuan wisata": "Tourist Destinations",
    "tv & video": "TV & Video",
    "tv and video": "TV & Video",
    "tv 및 동영상": "TV & Video",
    "uncategorised": "Uncategorized",
    "uncategorized": "Uncategorized",
    "unknown": "Uncategorized",
    "unspecified": "Uncategorized",
    "vehicle codes and driving laws": "Vehicle Codes & Driving Laws",
    "vehicle parts and services": "Vehicle Parts & Services",
    "violence and abuse": "Violence & Abuse",
    "visual art and design": "Visual Art & Design",
    "voice and video chat": "Voice & Video Chat",
    "vpn & akses jarak jauh": "VPN & Remote Access",
    "vpn and remote access": "VPN & Remote Access",
    "vpn 和远程访问": "VPN & Remote Access",
    "vpn 및 원격 액세스": "VPN & Remote Access",
    "war and conflict": "War & Conflict",
    "web apps and online tools": "Web Apps & Online Tools",
    "web design and development": "Web Design & Development",
    "web hosting and domain registration": "Web Hosting & Domain Registration",
    "web stats and analytics": "Web Stats & Analytics",
    "wholesalers and liquidators": "Wholesalers & Liquidators",
    "yayasan kesehatan & penelitian medis": "Health Foundations & Medical Research",
    "おもちゃ": "Toys",
    "お祝い、ギフト、祝祭日用グッズ": "Gifts & Special Event Items",
    "なし": "Uncategorized",
    "アウトドア": "Outdoors",
    "アニマル スポーツ": "Animal Sports",
    "アフィリエイト プログラム": "Affiliate Programs",
    "アルコール飲料": "Alcoholic Beverages",
    "アンティーク、コレクション": "Antiques & Collectibles",
    "アーケード ゲーム、コインゲーム": "Arcade & Coin-Op Games",
    "イベント情報": "Events & Listings",
    "インターネット、テクノロジー": "Internet & Technology",
    "インターンシップ": "Internships",
    "ウィンター スポーツ": "Winter Sports",
    "ウェブ アプリケーション、オンライン ツール": "Web Apps & Online Tools",
    "ウェブ ホスティング、ドメイン登録": "Web Hosting & Domain Registration",
    "ウェブデザイン、ウェブ開発": "Web Design & Development",
    "ウェブ解析": "Web Stats & Analytics",
    "ウォーター アクティビティ": "Water Activities",
    "ウォーター スポーツ": "Water Sports",
    "エクストリーム スポーツ": "Extreme Sports",
    "エネルギー、公共事業": "Energy & Utilities",
    "エンジニアリング、テクノロジー": "Engineering & Technology",
    "エンターテイメント メディア": "Entertainment Media",
    "エンターテイメント業": "Entertainment Industry",
    "オンライン コミュニティ": "Online Communities",
    "オンライン ツール、ダウンロード": "Online Goodies",
    "オンライン メディア": "Online Media",
    "オークション": "Auctions",
    "オーディオブック": "Audiobooks",
    "オープンソース": "Open Source",
    "カスタムカー、高性能車": "Custom & Performance Vehicles",
    "カテゴリなし": "Uncategorized",
    "カードゲーム": "Card Games",
    "キッチン、ダイニング": "Kitchen & Dining",
    "キャンピング カー、rv": "Campers & RVs",
    "ギャンブル": "Gambling",
    "クイズ、雑学": "Fun & Trivia",
    "クラウド ストレージ": "Cloud Storage",
    "クラウドファンディング": "Crowdfunding",
    "クラッシック カー": "Classic Vehicles",
    "クラブ、団体": "Clubs & Organizations",
    "クレジット、貸付": "Credit & Lending",
    "グリーン、エコフレンドリー ショッピング": "Green & Eco-Friendly Shopping",
    "ゲーム": "Games",
    "コミック、アニメ": "Comics & Animation",
    "コラボレーション、会議用ソフトウェア": "Collaboration & Conferencing",
    "コンテンツ管理": "Content Management",
    "コンピュータ ゲーム、ビデオゲーム": "Computer & Video Games",
    "コンピュータ サイエンス": "Computer Science",
    "コンピュータ セキュリティ": "Computer Security",
    "コンピュータ ハードウェア": "Computer Hardware",
    "ゴシップ、タブロイド ニュース": "Gossip & Tabloid News",
    "サブカルチャー": "Subcultures & Niche Interests",
    "サービス プロバイダ": "Service Providers",
    "サービス業": "Hospitality Industry",
    "ショッピング": "Shopping",
    "ショッピング総合サイト": "Shopping Portals",
    "ジャーナリズム、報道界": "Journalism & News Industry",
    "スポーツ": "Sports",
    "スポーツ ニュース": "Sports News",
    "スポーツのスコア、統計": "Sport Scores & Statistics",
    "スポーツの国際大会": "International Sports Competitions",
    "スポーツファン向けグッズ、衣料": "Sports Fan Gear & Apparel",
    "スポーツ指導、トレーニング": "Sports Coaching & Training",
    "スポーツ用品": "Sporting Goods",
    "ソフトウェア": "Software",
    "ソーシャル ネットワーク": "Social Networks",
    "タイルゲーム": "Tile Games",
    "タバコ、電子タバコ関連商品": "Tobacco & Vaping Products",
    "ダイスゲーム": "Dice Games",
    "テキスト メッセージ、インスタント メッセージ": "Text & Instant Messaging",
    "テクニカル情報": "Technical Reference",
    "テクノロジー関連のニュース": "Technology News",
    "テレビ、ビデオ、動画": "TV & Video",
    "テレビ会議": "Teleconferencing",
    "テーマ旅行": "Specialty Travel",
    "ディスカウント店、アウトレット店": "Discount & Outlet Stores",
    "デジタル通貨": "Digital Currencies",
    "デベロッパー": "Property Development",
    "デリケートなトピック": "Sensitive Subjects",
    "ニュース": "News",
    "ニュース放送": "Broadcast & Network News",
    "ネットワーキング": "Networking",
    "ハッキング、クラッキング": "Hacking & Cracking",
    "バーチャル プライベート ネットワーク(vpn)、リモート アクセス": "VPN & Remote Access",
    "パズル、頭脳ゲーム": "Puzzles & Brainteasers",
    "パティオ、芝生、庭": "Patio, Lawn & Garden",
    "パーティゲーム": "Party Games",
    "ビジネス スクール": "Business Education",
    "ビジネス ニュース": "Business News",
    "ビジネス、生産性ソフトウェア": "Business & Productivity Software",
    "ビジネス、産業": "Business & Industrial",
    "ビジュアル アート、デザイン": "Visual Art & Design",
    "ファイナンス": "Finance",
    "ファイル共有、ファイル ストレージ": "File Sharing & Hosting",
    "ファッション": "Apparel",
    "ファッション、スタイル": "Fashion & Style",
    "ファンタジー スポーツ": "Fantasy Sports",
    "フィットネス": "Fitness",
    "フィード アグリゲーション、ソーシャル ブックマーク": "Social Bookmarking",
    "フェイス、ボディケア": "Face & Body Care",
    "フリーウェア、シェアウェア": "Freeware & Shareware",
    "フリーマーケット、ガレージセール": "Swap Meets & Outdoor Markets",
    "ブランド品、高級品": "Luxury Goods",
    "ブログサービス": "Blogging",
    "プロキシ、フィルタ": "Proxying & Filtering",
    "プログラミング": "Programming",
    "ヘアケア": "Hair Care",
    "ヘルスケア": "Health Conditions",
    "ペイントボール": "Paintball",
    "ペット": "Pets",
    "ペット、動物": "Pets & Animals",
    "ペット用品、サービス": "Animal Products & Services",
    "ホテル、宿泊施設": "Hotels & Accommodations",
    "ホーム セキュリティ": "Home Safety & Security",
    "ボイスチャット、ビデオチャット": "Voice & Video Chat",
    "ボディアート": "Body Art",
    "ボート、水上の乗り物": "Boats & Watercraft",
    "ボードゲーム": "Board Games",
    "ポータルサイト": "Web Portals",
    "メンタルヘルス": "Mental Health",
    "メール": "Email",
    "メール、メッセージ": "Email & Messaging",
    "メールを送信": "Email",
    "メールアドレス": "Email",
    "モーター スポーツ": "Motor Sports",
    "モーターショー、オートショー": "Vehicle Shows",
    "ユーモア": "Humor",
    "ラジコン、模型": "Radio Control & Modeling",
    "ランドリー": "Laundry",
    "リフォーム": "Home Improvement",
    "リプロダクティブ ヘルス": "Reproductive Health",
    "レジャー飛行": "Recreational Aviation",
    "ロールプレイング ゲーム": "Roleplaying Games",
    "ワードゲーム": "Word Games",
    "一般参考信息": "General Reference",
    "一般資料": "General Reference",
    "不動産": "Real Estate",
    "不動産サービス": "Real Estate Services",
    "不動産情報": "Real Estate Listings",
    "不明": "Uncategorized",
    "专业与行业协会": "Professional & Trade Associations",
    "世界のニュース": "World News",
    "个人运动": "Individual Sports",
    "个性化内容": "Online Goodies",
    "事故、災害": "Accidents & Disasters",
    "事故与灾难": "Accidents & Disasters",
    "事業運営": "Business Operations",
    "二手市场与户外市场": "Swap Meets & Outdoor Markets",
    "二次創作": "Fan Fiction",
    "云存储": "Cloud Storage",
    "云端存储": "Cloud Storage",
    "互联网与科技": "Internet & Technology",
    "亚文化与小众话题": "Subcultures & Niche Interests",
    "交通": "Transportation",
    "交通法規": "Vehicle Codes & Driving Laws",
    "人々、社会": "People & Society",
    "人与社会": "People & Society",
    "人体艺术": "Body Art",
    "人文科学": "Humanities",
    "仕事、教育": "Jobs & Education",
    "代替医療、自然療法": "Alternative & Natural Medicine",
    "仮想空間": "Virtual Worlds",
    "企业技术": "Enterprise Technology",
    "企业财务": "Business Finance",
    "企業向けサービス": "Business Services",
    "企業向けテクノロジー": "Enterprise Technology",
    "企業金融": "Business Finance",
    "休闲飞行": "Recreational Aviation",
    "众筹": "Crowdfunding",
    "会計、監査": "Accounting & Auditing",
    "会计与审计": "Accounting & Auditing",
    "住まい、園芸": "Home & Garden",
    "体育": "Sports",
    "体育指导与训练": "Sports Coaching & Training",
    "体育新闻": "Sports News",
    "体育用品": "Sporting Goods",
    "作家、ライター向け情報": "Writers Resources",
    "保险": "Insurance",
    "保険": "Insurance",
    "信贷": "Credit & Lending",
    "俱乐部与社团": "Clubs & Organizations",
    "個人ブログ、サイト": "Online Journals & Personal Sites",
    "個人広告": "Classifieds",
    "個人競技": "Individual Sports",
    "健康": "Health",
    "健康に関するニュース": "Health News",
    "健康基金会与医疗研究机构": "Health Foundations & Medical Research",
    "健康教育、医療トレーニング": "Health Education & Medical Training",
    "健康教育与医疗培训": "Health Education & Medical Training",
    "健康资讯": "Health News",
    "健康问题": "Health Conditions",
    "健身": "Fitness",
    "優秀賞、コンテスト": "Merit Prizes & Contests",
    "儿科": "Pediatrics",
    "儿童与青少年": "Kids & Teens",
    "儿童文学": "Children's Literature",
    "免费软件和共享软件": "Freeware & Shareware",
    "児童文学": "Children's Literature",
    "八卦与小报新闻": "Gossip & Tabloid News",
    "公共の安全": "Public Safety",
    "公共卫生": "Public Health",
    "公共安全": "Public Safety",
    "公衆衛生": "Public Health",
    "内容管理": "Content Management",
    "写作资源": "Writers Resources",
    "写真、ビデオ撮影": "Photo & Video Services",
    "写真、動画共有": "Photo & Video Sharing",
    "军事": "Military",
    "农业与林业": "Agriculture & Forestry",
    "冬季运动": "Winter Sports",
    "减肥": "Weight Loss",
    "出会い": "Dating & Personals",
    "分类广告": "Classifieds",
    "制药与生物科技": "Pharmaceuticals & Biotech",
    "制造业": "Manufacturing",
    "动漫": "Comics & Animation",
    "动物用品与服务": "Animal Products & Services",
    "动物运动": "Animal Sports",
    "助学金、奖学金与经济资助": "Grants, Scholarships & Financial Aid",
    "励志自助": "Self-Help & Motivational",
    "化学": "Chemistry",
    "化学産業": "Chemicals Industry",
    "化工业": "Chemicals Industry",
    "医学文献、資料": "Medical Literature & Resources",
    "医疗器械与设备": "Medical Devices & Equipment",
    "医疗文献与资源": "Medical Literature & Resources",
    "医疗设施与服务": "Medical Facilities & Services",
    "医療施設、医療サービス": "Medical Facilities & Services",
    "医療装置、医療機器": "Medical Devices & Equipment",
    "医療財団、医療研究所": "Health Foundations & Medical Research",
    "医薬品、バイオテクノロジー": "Pharmaceuticals & Biotech",
    "协作与会议软件": "Collaboration & Conferencing",
    "卓上ゲーム": "Table Games",
    "博客资源和服务": "Blogging",
    "卧室与卫浴": "Bed & Bath",
    "印刷、出版": "Printing & Publishing",
    "印刷与出版": "Printing & Publishing",
    "危険ドラッグ": "Recreational Drugs",
    "卸売業者、在庫管理": "Wholesalers & Liquidators",
    "厨房和餐厅": "Kitchen & Dining",
    "参考信息": "Reference",
    "发廊": "Hair Care",
    "发送电子邮件": "Email",
    "口腔、デンタルケア": "Oral & Dental Care",
    "口腔与牙科保健": "Oral & Dental Care",
    "古典文学": "Literary Classics",
    "古董与收藏品": "Antiques & Collectibles",
    "各種リスト、住所録、要覧": "Directories & Listings",
    "同人小说": "Fan Fiction",
    "名人和娱乐新闻": "Celebrities & Entertainment News",
    "商业与工业": "Business & Industrial",
    "商业教育": "Business Education",
    "商业新闻": "Business News",
    "商业服务": "Business Services",
    "商务与办公软件": "Business & Productivity Software",
    "商务车": "Commercial Vehicles",
    "商用自動車": "Commercial Vehicles",
    "团队运动": "Team Sports",
    "団体競技": "Team Sports",
    "図書館、博物館": "Libraries & Museums",
    "国际体育竞赛": "International Sports Competitions",
    "国际新闻": "World News",
    "图书与文学": "Books & Literature",
    "图书零售商": "Book Retailers",
    "图书馆与博物馆": "Libraries & Museums",
    "在线媒体": "Online Media",
    "在线日志与个人网站": "Online Journals & Personal Sites",
    "在线社区": "Online Communities",
    "地域ニュース": "Local News",
    "地方新闻": "Local News",
    "地球科学": "Earth Sciences",
    "地理参考信息": "Geographic Reference",
    "地理資料": "Geographic Reference",
    "垃圾讯息": "Electronic Spam",
    "大卖场及百货公司": "Mass Merchants & Department Stores",
    "大学スポーツ": "College Sports",
    "大学体育": "College Sports",
    "天文学": "Astronomy",
    "天气": "Weather",
    "天気": "Weather",
    "失踪与绑架": "Missing Persons & Abductions",
    "奇妙": "Offbeat",
    "奖品与竞赛": "Merit Prizes & Contests",
    "奢侈品": "Luxury Goods",
    "奨学金、補助金": "Grants, Scholarships & Financial Aid",
    "女性の健康": "Women's Health",
    "女性健康": "Women's Health",
    "娱乐业": "Entertainment Industry",
    "娱乐媒体": "Entertainment Media",
    "学習ゲーム": "Educational Games",
    "宗教、信仰": "Religion & Belief",
    "宗教与信仰": "Religion & Belief",
    "定制车与高性能车": "Custom & Performance Vehicles",
    "实习": "Internships",
    "宠物": "Pets",
    "宠物与动物": "Pets & Animals",
    "室内装飾、内装": "Home & Interior Decor",
    "害虫控制": "Pest Control",
    "害虫駆除": "Pest Control",
    "家事代行サービス": "Domestic Services",
    "家具": "Home Furnishings",
    "家居与园艺": "Home & Garden",
    "家居与室内装潢": "Home & Interior Decor",
    "家居安全与安保": "Home Safety & Security",
    "家居改造": "Home Improvement",
    "家居用品": "Household Supplies",
    "家庭与人际关系": "Family & Relationships",
    "家庭储藏和搁架": "Home Storage & Shelving",
    "家庭向け収納整理用品": "Home Storage & Shelving",
    "家庭泳池、桑拿和水疗": "Swimming Pools, Saunas & Spas",
    "家庭用スイミング プール、サウナ、スパ": "Swimming Pools, Saunas & Spas",
    "家政服务": "Domestic Services",
    "家族、人間関係": "Family & Relationships",
    "家族向けゲーム、アクティビティ": "Family-Oriented Games & Activities",
    "家用电器": "Home Appliances",
    "家電": "Consumer Electronics",
    "寝具、バス用品": "Bed & Bath",
    "専門家、業界団体": "Professional & Trade Associations",
    "小児科": "Pediatrics",
    "小型企业": "Small Business",
    "小売業": "Retail Trade",
    "小規模ビジネス": "Small Business",
    "工业材料与设备": "Industrial Materials & Equipment",
    "工作": "Jobs",
    "工作与教育": "Jobs & Education",
    "工程与技术": "Engineering & Technology",
    "工芸品": "Crafts",
    "幽默": "Humor",
    "广告与市场营销": "Advertising & Marketing",
    "广播与网络新闻": "Broadcast & Network News",
    "広告、マーケティング": "Advertising & Marketing",
    "庭院、草坪和花园": "Patio, Lawn & Garden",
    "建設業、保守管理": "Construction & Maintenance",
    "开放源代码": "Open Source",
    "彩弹射击": "Paintball",
    "心理健康": "Mental Health",
    "懸賞": "Sweepstakes & Promotional Giveaways",
    "成人": "Adult",
    "成人向け": "Adult",
    "战争与冲突": "War & Conflict",
    "戦争、紛争": "War & Conflict",
    "户外活动": "Outdoors",
    "房地产": "Real Estate",
    "房地产开发": "Property Development",
    "房地产服务": "Real Estate Services",
    "房源信息": "Real Estate Listings",
    "手工艺品": "Crafts",
    "批发与清仓": "Wholesalers & Liquidators",
    "技术参考信息": "Technical Reference",
    "投資": "Investing",
    "投资": "Investing",
    "折扣店和直销店": "Discount & Outlet Stores",
    "护理": "Nursing",
    "报纸": "Newspapers",
    "抽奖奖品和促销赠品": "Sweepstakes & Promotional Giveaways",
    "拍卖": "Auctions",
    "拼图游戏": "Tile Games",
    "指定なし": "Uncategorized",
    "掲示板、チャット": "Forum & Chat Providers",
    "搜索引擎": "Search Engines",
    "搜索引擎优化与营销": "Search Engine Optimization",
    "携帯、ワイヤレス": "Mobile & Wireless",
    "政府": "Government",
    "政府機関": "Government",
    "政治": "Politics",
    "敏感主题": "Sensitive Subjects",
    "教育": "Education",
    "教育ソフトウェア": "Educational Software",
    "教育版": "Education",
    "教育软件": "Educational Software",
    "数字货币": "Digital Currencies",
    "数学": "Mathematics",
    "文件共享与托管": "File Sharing & Hosting",
    "文字游戏": "Word Games",
    "文学经典": "Literary Classics",
    "料理、レシピ": "Cooking & Recipes",
    "新聞": "Newspapers",
    "新闻": "News",
    "新闻工作与新闻行业": "Journalism & News Industry",
    "施工与维护": "Construction & Maintenance",
    "旅游景点": "Tourist Destinations",
    "旅行、運輸": "Travel & Transportation",
    "旅行ガイド、旅行記": "Travel Guides & Travelogues",
    "旅行バッグ、旅行用品": "Luggage & Travel Accessories",
    "旅行与交通": "Travel & Transportation",
    "旅行代理店、旅行サービス": "Travel Agencies & Services",
    "旅行指南与游记": "Travel Guides & Travelogues",
    "旅行社与旅行服务": "Travel Agencies & Services",
    "无": "Uncategorized",
    "无线电遥控与建模": "Radio Control & Modeling",
    "日用品": "Household Supplies",
    "映画": "Movies",
    "暖通空调和环境控制": "HVAC & Climate Control",
    "暴力、虐待": "Violence & Abuse",
    "暴力与骚扰": "Violence & Abuse",
    "書籍、文学": "Books & Literature",
    "書籍販売": "Book Retailers",
    "替代疗法与自然医学": "Alternative & Natural Medicine",
    "有声读物": "Audiobooks",
    "服务提供商": "Service Providers",
    "服饰": "Apparel",
    "未分类": "Uncategorized",
    "未指定": "Uncategorized",
    "未知": "Uncategorized",
    "机动车": "Motor Vehicles",
    "杂志": "Magazines",
    "极限运动": "Extreme Sports",
    "枪支与武器": "Firearms & Weapons",
    "栄養": "Nutrition",
    "格斗运动": "Combat Sports",
    "格闘技": "Combat Sports",
    "桌上球类运动": "Table Games",
    "桌游": "Board Games",
    "梦幻运动游戏": "Fantasy Sports",
    "検索エンジン": "Search Engines",
    "死亡与悲剧性事件": "Death & Tragedy",
    "残疾人与特殊需求": "Disabled & Special Needs",
    "比赛得分与统计数据": "Sport Scores & Statistics",
    "民族、思想": "Ethnic & Identity Groups",
    "水上活动": "Water Activities",
    "水上运动": "Water Sports",
    "汽车与其他交通工具": "Autos & Vehicles",
    "汽车业": "Automotive Industry",
    "汽车运动": "Motor Sports",
    "法务": "Legal",
    "法務": "Legal",
    "法律、行政": "Law & Government",
    "法律与政府": "Law & Government",
    "洗衣设施": "Laundry",
    "活动与演出信息": "Events & Listings",
    "派对游戏": "Party Games",
    "流行与时尚": "Fashion & Style",
    "消費者資源": "Consumer Resources",
    "消费类电子产品": "Consumer Electronics",
    "消费者资源": "Consumer Resources",
    "消遣性药物": "Recreational Drugs",
    "減量": "Weight Loss",
    "游戏": "Games",
    "烟草和电子烟商品": "Tobacco & Vaping Products",
    "烹饪与食谱": "Cooking & Recipes",
    "照片与视频分享": "Photo & Video Sharing",
    "照片与视频服务": "Photo & Video Services",
    "爱好与休闲": "Hobbies & Leisure",
    "物理学": "Physics",
    "特殊场合": "Special Occasions",
    "特色旅游": "Specialty Travel",
    "玩具": "Toys",
    "理容学校、美容学校": "Cosmetology & Beauty Professionals",
    "生态与环境": "Ecology & Environment",
    "生態学、環境": "Ecology & Environment",
    "生成 ai": "Generative AI",
    "生成式 ai": "Generative AI",
    "生殖健康": "Reproductive Health",
    "生活家電用品": "Home Appliances",
    "生物学": "Biological Sciences",
    "生物科学": "Biological Sciences",
    "産業資材、設備": "Industrial Materials & Equipment",
    "电子与电气": "Electronics & Electrical",
    "电子书": "E-Books",
    "电子邮件": "Email",
    "电子邮件和消息通讯": "Email & Messaging",
    "电子邮件地址": "Email",
    "电影": "Movies",
    "电视与视频": "TV & Video",
    "电话会议": "Teleconferencing",
    "男性の健康": "Men's Health",
    "男性健康": "Men's Health",
    "益智游戏": "Educational Games",
    "目录和列表": "Directories & Listings",
    "看護": "Nursing",
    "眼科": "Vision Care",
    "短信和即时通讯": "Text & Instant Messaging",
    "礼品与特殊活动用品": "Gifts & Special Event Items",
    "礼宾行业": "Hospitality Industry",
    "社交网络": "Social Networks",
    "社会問題、支援運動": "Social Issues & Advocacy",
    "社会服务": "Social Services",
    "社会福祉": "Social Services",
    "社会科学": "Social Sciences",
    "社会问题与宣传": "Social Issues & Advocacy",
    "私人飞机": "Personal Aircraft",
    "种族与认同群体": "Ethnic & Identity Groups",
    "科学": "Science",
    "科学機関": "Scientific Institutions",
    "科学装置": "Scientific Equipment",
    "科学设备": "Scientific Equipment",
    "科技新闻": "Technology News",
    "科研机构": "Scientific Institutions",
    "移动与无线": "Mobile & Wireless",
    "空調設備、温度調整器": "HVAC & Climate Control",
    "織物、不織布": "Textiles & Nonwovens",
    "约会与交友": "Dating & Personals",
    "纸牌游戏": "Card Games",
    "纺织品与无纺织物": "Textiles & Nonwovens",
    "经典车型": "Classic Vehicles",
    "经营活动": "Business Operations",
    "绿色环保型购物": "Green & Eco-Friendly Shopping",
    "编程": "Programming",
    "网站托管与域名注册": "Web Hosting & Domain Registration",
    "网站统计与分析": "Web Stats & Analytics",
    "网络": "Networking",
    "网络代理与过滤": "Proxying & Filtering",
    "网络奇闻": "Offbeat",
    "网络应用与在线工具": "Web Apps & Online Tools",
    "网络设计与开发": "Web Design & Development",
    "网络门户": "Web Portals",
    "美人コンテスト": "Beauty Pageants",
    "美容、フィットネス": "Beauty & Fitness",
    "美容サービス、スパ": "Beauty Services & Spas",
    "美容与健身": "Beauty & Fitness",
    "美容业与美容专家": "Cosmetology & Beauty Professionals",
    "美容服务和水疗按摩": "Beauty Services & Spas",
    "美食": "Food",
    "老化、高齢者医療": "Aging & Geriatrics",
    "老龄人与退休": "Seniors & Retirement",
    "老龄化与老年病学": "Aging & Geriatrics",
    "联署营销计划": "Affiliate Programs",
    "職業紹介、求人情報": "Jobs",
    "能源与公用事业": "Energy & Utilities",
    "自傷行為": "Self-Harm",
    "自動車": "Motor Vehicles",
    "自動車、乗り物": "Autos & Vehicles",
    "自動車産業": "Automotive Industry",
    "自動車販売": "Vehicle Shopping",
    "自動車部品、サービス": "Vehicle Parts & Services",
    "自家用航空機": "Personal Aircraft",
    "自残": "Self-Harm",
    "自立、自己啓発": "Self-Help & Motivational",
    "自行车与配件": "Bicycles & Accessories",
    "自転車、パーツ": "Bicycles & Accessories",
    "舞台芸術": "Performing Arts",
    "航空、防衛": "Aerospace & Defense",
    "航空航天与国防": "Aerospace & Defense",
    "船舶与水运工具": "Boats & Watercraft",
    "艺术与娱乐": "Arts & Entertainment",
    "芸能、エンターテイメント ニュース": "Celebrities & Entertainment News",
    "芸術、エンターテイメント": "Arts & Entertainment",
    "药品": "Pharmacy",
    "药物滥用": "Substance Abuse",
    "营养": "Nutrition",
    "薬局": "Pharmacy",
    "薬物乱用": "Substance Abuse",
    "虚拟世界": "Virtual Worlds",
    "行事": "Special Occasions",
    "行方不明、誘拐事件": "Missing Persons & Abductions",
    "行李和旅行用品": "Luggage & Travel Accessories",
    "街机游戏和投币游戏": "Arcade & Coin-Op Games",
    "表演艺术": "Performing Arts",
    "製造": "Manufacturing",
    "観光名所": "Tourist Destinations",
    "视力保健": "Vision Care",
    "视觉艺术与设计": "Visual Art & Design",
    "角色扮演游戏": "Roleplaying Games",
    "解谜与益智游戏": "Puzzles & Brainteasers",
    "言語資料": "Language Resources",
    "訃報、悲報": "Death & Tragedy",
    "詩": "Poetry",
    "计算机和视频游戏": "Computer & Video Games",
    "计算机安全": "Computer Security",
    "计算机硬件": "Computer Hardware",
    "计算机科学": "Computer Science",
    "论坛与聊天服务": "Forum & Chat Providers",
    "诗歌": "Poetry",
    "语言资源": "Language Resources",
    "財務プランニング、マネジメント": "Financial Planning & Management",
    "資料": "Reference",
    "财务": "Finance",
    "财务规划与管理": "Financial Planning & Management",
    "购物": "Shopping",
    "购物门户": "Shopping Portals",
    "购车": "Vehicle Shopping",
    "赌博": "Gambling",
    "趣事逸闻": "Fun & Trivia",
    "趣味、レジャー": "Hobbies & Leisure",
    "軍事": "Military",
    "车展": "Vehicle Shows",
    "车辆法规与交通法": "Vehicle Codes & Driving Laws",
    "车辆零部件和服务": "Vehicle Parts & Services",
    "软件": "Software",
    "農林業": "Agriculture & Forestry",
    "运动爱好者装备和服装": "Sports Fan Gear & Apparel",
    "运输和物流": "Shipping & Logistics",
    "选美大赛": "Beauty Pageants",
    "通信機器": "Communications Equipment",
    "通信设备": "Communications Equipment",
    "邮件": "Email",
    "邮箱": "Email",
    "配送、物流": "Shipping & Logistics",
    "酒店与住宿": "Hotels & Accommodations",
    "酒精饮料": "Alcoholic Beverages",
    "野生动植物": "Wildlife",
    "野生動物": "Wildlife",
    "野营挂车和休闲车": "Campers & RVs",
    "量販店、デパート": "Mass Merchants & Department Stores",
    "金属、鉱業": "Metals & Mining",
    "金属与采矿": "Metals & Mining",
    "銀行業": "Banking",
    "銃、武器": "Firearms & Weapons",
    "银行": "Banking",
    "障がい者、特別支援": "Disabled & Special Needs",
    "雑誌": "Magazines",
    "零售业": "Retail Trade",
    "電子スパム": "Electronic Spam",
    "電子書籍": "E-Books",
    "電子機器、電気機器": "Electronics & Electrical",
    "青少年向けコンテンツ": "Kids & Teens",
    "面向家庭的游戏和活动": "Family-Oriented Games & Activities",
    "面部及身体护理": "Face & Body Care",
    "音乐与音频": "Music & Audio",
    "音楽、オーディオ": "Music & Audio",
    "音频和视频聊天": "Voice & Video Chat",
    "食品、飲料": "Food & Drink",
    "食品杂货配送": "Food & Grocery Delivery",
    "食品杂货零售商": "Food & Grocery Retailers",
    "食料品": "Food",
    "食料雑貨の小売業": "Food & Grocery Retailers",
    "食料雑貨の配達": "Food & Grocery Delivery",
    "飲料": "Beverages",
    "飲食店": "Restaurants",
    "餐饮": "Food & Drink",
    "餐馆": "Restaurants",
    "饮料": "Beverages",
    "骰子游戏": "Dice Games",
    "高齢者、老後の暮らし": "Seniors & Retirement",
    "黑客与破解": "Hacking & Cracking",
    "가사 서비스": "Domestic Services",
    "가상 세계": "Virtual Worlds",
    "가십 및 타블로이드 뉴스": "Gossip & Tabloid News",
    "가전제품": "Home Appliances",
    "가정 비품": "Home Furnishings",
    "가정용 수납 및 선반": "Home Storage & Shelving",
    "가정용 수영장, 사우나, 스파": "Swimming Pools, Saunas & Spas",
    "가정용품": "Household Supplies",
    "가족 및 연인": "Family & Relationships",
    "가족용 게임 및 활동": "Family-Oriented Games & Activities",
    "가택 경비 및 보안": "Home Safety & Security",
    "간호": "Nursing",
    "개별 스포츠": "Individual Sports",
    "개인용 항공기": "Personal Aircraft",
    "건강": "Health",
    "건강 관련 뉴스": "Health News",
    "건강 교육 및 의료 훈련": "Health Education & Medical Training",
    "건강 상태": "Health Conditions",
    "건축 및 유지보수": "Construction & Maintenance",
    "검색엔진": "Search Engines",
    "검색엔진 최적화 및 마케팅": "Search Engine Optimization",
    "게임": "Games",
    "격투기": "Combat Sports",
    "경기 점수 및 통계": "Sport Scores & Statistics",
    "경매": "Auctions",
    "경영 금융": "Business Finance",
    "경품 및 판촉 증정품": "Sweepstakes & Promotional Giveaways",
    "고전문학": "Literary Classics",
    "골동품 및 수집품": "Antiques & Collectibles",
    "공공 안전": "Public Safety",
    "공연 예술": "Performing Arts",
    "공예": "Crafts",
    "공중 보건": "Public Health",
    "과학": "Science",
    "과학 기관": "Scientific Institutions",
    "과학 장비": "Scientific Equipment",
    "관광지 정보": "Tourist Destinations",
    "광고 및 마케팅": "Advertising & Marketing",
    "교육": "Education",
    "교육용 게임": "Educational Games",
    "교육용 소프트웨어": "Educational Software",
    "교통": "Transportation",
    "구강 및 치아 관리": "Oral & Dental Care",
    "국제 뉴스": "World News",
    "국제 스포츠 대회": "International Sports Competitions",
    "군대": "Military",
    "금속 및 광업": "Metals & Mining",
    "기념일": "Special Occasions",
    "기분전환용 약물": "Recreational Drugs",
    "기술 관련 뉴스": "Technology News",
    "기술 관련 자료": "Technical Reference",
    "날씨": "Weather",
    "남성 건강": "Men's Health",
    "낱말 놀이": "Word Games",
    "냉난방 및 온도 조절": "HVAC & Climate Control",
    "네트워킹": "Networking",
    "노인 및 은퇴": "Seniors & Retirement",
    "노화 및 노인질환": "Aging & Geriatrics",
    "녹색소비 및 친환경 쇼핑": "Green & Eco-Friendly Shopping",
    "농업 및 임업": "Agriculture & Forestry",
    "뉴스": "News",
    "담배 및 전자담배 제품": "Tobacco & Vaping Products",
    "대체 및 자연 의학": "Alternative & Natural Medicine",
    "대학 스포츠": "College Sports",
    "대형 할인점 및 백화점": "Mass Merchants & Department Stores",
    "도매업자 및 청산인": "Wholesalers & Liquidators",
    "도박": "Gambling",
    "도서 및 문학": "Books & Literature",
    "도서관 및 박물관": "Libraries & Museums",
    "동계 스포츠": "Winter Sports",
    "동물 관련 스포츠": "Animal Sports",
    "동물 제품 및 서비스": "Animal Products & Services",
    "디렉터리 및 등록정보": "Directories & Listings",
    "디지털 통화": "Digital Currencies",
    "롤플레잉 게임": "Roleplaying Games",
    "리걸": "Legal",
    "만남 및 데이트": "Dating & Personals",
    "만화 및 애니메이션": "Comics & Animation",
    "모바일 및 무선": "Mobile & Wireless",
    "모발 관리": "Hair Care",
    "모터 스포츠": "Motor Sports",
    "무선 조종 및 모형 제작": "Radio Control & Modeling",
    "문자 및 채팅 메시지": "Text & Instant Messaging",
    "물리학": "Physics",
    "미용 및 건강": "Beauty & Fitness",
    "미인 대회": "Beauty Pageants",
    "민감한 주제": "Sensitive Subjects",
    "바디아트": "Body Art",
    "반려동물": "Pets",
    "반려동물 및 동물": "Pets & Animals",
    "발코니, 잔디, 정원 관리": "Patio, Lawn & Garden",
    "방송 및 네트워크 뉴스": "Broadcast & Network News",
    "배송 및 물류": "Shipping & Logistics",
    "법무": "Legal",
    "벼룩시장 및 노천시장": "Swap Meets & Outdoor Markets",
    "보드게임": "Board Games",
    "보조금, 장학금, 재정 지원": "Grants, Scholarships & Financial Aid",
    "보트 및 선박": "Boats & Watercraft",
    "보험": "Insurance",
    "부동산": "Real Estate",
    "부동산 개발": "Property Development",
    "부동산 매물": "Real Estate Listings",
    "부동산 서비스": "Real Estate Services",
    "뷰티 및 미용 전문가": "Cosmetology & Beauty Professionals",
    "뷰티 서비스 및 스파": "Beauty Services & Spas",
    "블로그 리소스 및 서비스": "Blogging",
    "비주류 집단 및 틈새 집단": "Subcultures & Niche Interests",
    "비즈니스 교육": "Business Education",
    "비즈니스 뉴스": "Business News",
    "비즈니스 및 산업": "Business & Industrial",
    "비즈니스 및 생산성 소프트웨어": "Business & Productivity Software",
    "비즈니스 서비스": "Business Services",
    "비즈니스 운영": "Business Operations",
    "사고 및 재난": "Accidents & Disasters",
    "사망 및 참사": "Death & Tragedy",
    "사법 및 정부 기관": "Law & Government",
    "사진 및 동영상 공유": "Photo & Video Sharing",
    "사진 및 동영상 서비스": "Photo & Video Services",
    "사치품": "Luxury Goods",
    "사회 과학": "Social Sciences",
    "사회 문제 및 지원단체": "Social Issues & Advocacy",
    "사회복지 서비스": "Social Services",
    "산업자재 및 장비": "Industrial Materials & Equipment",
    "상업용 차량": "Commercial Vehicles",
    "생물학": "Biological Sciences",
    "생성형 ai": "Generative AI",
    "생식 건강": "Reproductive Health",
    "생태학•및 환경학": "Ecology & Environment",
    "서비스 제공업체": "Service Providers",
    "서점": "Book Retailers",
    "선물 및 특별 이벤트 항목": "Gifts & Special Event Items",
    "선택 안함": "Uncategorized",
    "성인": "Adult",
    "세탁": "Laundry",
    "소매거래": "Retail Trade",
    "소비자 가전": "Consumer Electronics",
    "소비자 리소스": "Consumer Resources",
    "소셜 네트워크": "Social Networks",
    "소아과": "Pediatrics",
    "소프트웨어": "Software",
    "쇼핑": "Shopping",
    "쇼핑 포털": "Shopping Portals",
    "수상 및 콘테스트": "Merit Prizes & Contests",
    "수상 스포츠": "Water Sports",
    "수학": "Mathematics",
    "스포츠": "Sports",
    "스포츠 뉴스": "Sports News",
    "스포츠 코칭 및 훈련": "Sports Coaching & Training",
    "스포츠용품": "Sporting Goods",
    "스포츠팀 로고 장비 및 의류": "Sports Fan Gear & Apparel",
    "시": "Poetry",
    "시각 예술 및 디자인": "Visual Art & Design",
    "시력 관리": "Vision Care",
    "식료품 및 생필품점": "Food & Grocery Retailers",
    "식음료": "Food & Drink",
    "신문": "Newspapers",
    "신용 및 대출": "Credit & Lending",
    "실종 및 납치": "Missing Persons & Abductions",
    "아동 및 청소년": "Kids & Teens",
    "아동문학": "Children's Literature",
    "아케이드 및 코인 게임": "Arcade & Coin-Op Games",
    "알 수 없음": "Uncategorized",
    "알코올성 음료": "Alcoholic Beverages",
    "야생동물": "Wildlife",
    "야외 활동": "Outdoors",
    "약물 남용": "Substance Abuse",
    "언어 관련 자료": "Language Resources",
    "얼굴 및 바디 관리": "Face & Body Care",
    "없음": "Uncategorized",
    "에너지 및 공공사업": "Energy & Utilities",
    "엔지니어링 및 기술": "Engineering & Technology",
    "엔터테인먼트 미디어": "Entertainment Media",
    "엔터테인먼트 산업": "Entertainment Industry",
    "엔터프라이즈 기술": "Enterprise Technology",
    "여성 건강": "Women's Health",
    "여행 가방 및 여행용품": "Luggage & Travel Accessories",
    "여행 가이드 및 여행기": "Travel Guides & Travelogues",
    "여행 및 교통수단": "Travel & Transportation",
    "여행사 및 여행 서비스": "Travel Agencies & Services",
    "영양": "Nutrition",
    "영화": "Movies",
    "예술 및 엔터테인먼트": "Arts & Entertainment",
    "오디오북": "Audiobooks",
    "오락 및 퀴즈": "Fun & Trivia",
    "오토바이": "Motor Vehicles",
    "오프비트": "Offbeat",
    "오픈소스": "Open Source",
    "온라인 미디어": "Online Media",
    "온라인 상품": "Online Goodies",
    "온라인 저널 및 개인 사이트": "Online Journals & Personal Sites",
    "온라인 커뮤니티": "Online Communities",
    "요리 및 조리법": "Cooking & Recipes",
    "웹 디자인 및 개발": "Web Design & Development",
    "웹 앱 및 온라인 도구": "Web Apps & Online Tools",
    "웹 통계 및 분석": "Web Stats & Analytics",
    "웹 포털": "Web Portals",
    "웹 호스팅 및 도메인 등록": "Web Hosting & Domain Registration",
    "유머": "Humor",
    "유명인 및 연예 소식": "Celebrities & Entertainment News",
    "은행": "Banking",
    "음료": "Beverages",
    "음성 및 영상 채팅": "Voice & Video Chat",
    "음식": "Food",
    "음식 및 식료품 배달": "Food & Grocery Delivery",
    "음식점": "Restaurants",
    "음악 및 오디오": "Music & Audio",
    "의료 기기 및 장비": "Medical Devices & Equipment",
    "의료 재단 및 의학 연구": "Health Foundations & Medical Research",
    "의료시설 및 서비스": "Medical Facilities & Services",
    "의류": "Apparel",
    "의약품": "Pharmacy",
    "의학 서적 및 자료": "Medical Literature & Resources",
    "이메일": "Email",
    "이메일 및 문자 메시지": "Email & Messaging",
    "이벤트 및 등록정보": "Events & Listings",
    "익스트림 스포츠": "Extreme Sports",
    "인문학": "Humanities",
    "인물 및 사회": "People & Society",
    "인쇄 및 출판": "Printing & Publishing",
    "인종 및 정체성 그룹": "Ethnic & Identity Groups",
    "인터넷 및 기술": "Internet & Technology",
    "인턴십": "Internships",
    "인테리어 및 정원": "Home & Garden",
    "일반 자료": "General Reference",
    "자기계발 및 동기부여": "Self-Help & Motivational",
    "자동차": "Autos & Vehicles",
    "자동차 부품•및 서비스": "Vehicle Parts & Services",
    "자동차 산업": "Automotive Industry",
    "자동차 쇼": "Vehicle Shows",
    "자동차 쇼핑": "Vehicle Shopping",
    "자선사업": "Hospitality Industry",
    "자전거 및 액세서리": "Bicycles & Accessories",
    "자해": "Self-Harm",
    "작문 정보": "Writers Resources",
    "잡지": "Magazines",
    "장난감": "Toys",
    "장애인": "Disabled & Special Needs",
    "재무": "Finance",
    "재무 설계 및 관리": "Financial Planning & Management",
    "저널리즘 및 뉴스 산업": "Journalism & News Industry",
    "전기 및 전자": "Electronics & Electrical",
    "전문가 및 무역 협회": "Professional & Trade Associations",
    "전자 스팸": "Electronic Spam",
    "전쟁 및 분쟁": "War & Conflict",
    "정부 기관": "Government",
    "정신 건강": "Mental Health",
    "정치": "Politics",
    "제약 및 바이오테크": "Pharmaceuticals & Biotech",
    "제조": "Manufacturing",
    "제조업": "Manufacturing",
    "제휴 프로그램": "Affiliate Programs",
    "종교 및 신앙": "Religion & Belief",
    "주방 및 식당": "Kitchen & Dining",
    "주사위 게임": "Dice Games",
    "중소기업": "Small Business",
    "지구과학": "Earth Sciences",
    "지역 뉴스": "Local News",
    "지역별 정보": "Geographic Reference",
    "직물 및 부직포": "Textiles & Nonwovens",
    "집 개조": "Home Improvement",
    "차량 및 운전 규제와 법률": "Vehicle Codes & Driving Laws",
    "참고자료": "Reference",
    "천문학": "Astronomy",
    "체중 감량": "Weight Loss",
    "체험 비행": "Recreational Aviation",
    "총기 및 무기": "Firearms & Weapons",
    "취미 및 레저": "Hobbies & Leisure",
    "취업정보": "Jobs",
    "취업정보 및 교육": "Jobs & Education",
    "침실 및 욕실": "Bed & Bath",
    "카드 게임": "Card Games",
    "카테고리 없음": "Uncategorized",
    "캠핑카 및 레저용 차량": "Campers & RVs",
    "커스텀 및 고성능 자동차": "Custom & Performance Vehicles",
    "컴퓨터 공학": "Computer Science",
    "컴퓨터 및 비디오 게임": "Computer & Video Games",
    "컴퓨터 보안": "Computer Security",
    "컴퓨터 하드웨어": "Computer Hardware",
    "콘텐츠 관리": "Content Management",
    "크라우드 펀딩": "Crowdfunding",
    "클라우드 스토리지": "Cloud Storage",
    "클래식카": "Classic Vehicles",
    "클럽 및 조직": "Clubs & Organizations",
    "타일 게임": "Tile Games",
    "테이블 게임": "Table Games",
    "통신 장비": "Communications Equipment",
    "투자": "Investing",
    "특수 관광": "Specialty Travel",
    "팀 스포츠": "Team Sports",
    "파일 공유 및 호스팅": "File Sharing & Hosting",
    "파티 게임": "Party Games",
    "판타지 스포츠": "Fantasy Sports",
    "패션 및 스타일": "Fashion & Style",
    "팬 픽션": "Fan Fiction",
    "퍼즐 및 두뇌 게임": "Puzzles & Brainteasers",
    "페인트볼": "Paintball",
    "포럼 및 채팅 서비스 제공업체": "Forum & Chat Providers",
    "폭력 및 학대": "Violence & Abuse",
    "프로그래밍": "Programming",
    "프록시 및 필터링": "Proxying & Filtering",
    "프리웨어 및 셰어웨어": "Freeware & Shareware",
    "피드 집계 및 소셜 북마크": "Social Bookmarking",
    "피트니스": "Fitness",
    "할인 및 아울렛 매장": "Discount & Outlet Stores",
    "항공우주 및 방위": "Aerospace & Defense",
    "항목별 광고": "Classifieds",
    "해충 퇴치": "Pest Control",
    "해킹 및 크래킹": "Hacking & Cracking",
    "협업 및 회의용 소프트웨어": "Collaboration & Conferencing",
    "호텔 및 숙박": "Hotels & Accommodations",
    "홈데코 및 인테리어": "Home & Interior Decor",
    "화상회의": "Teleconferencing",
    "화학": "Chemistry",
    "화학 산업": "Chemicals Industry",
    "회계 및 감사": "Accounting & Auditing"
  }
};

function ceraNormConsoleKey_(val) {
  if (val === null || val === undefined || val === '') return '';
  return String(val).normalize('NFKC').replace(/\s+/g, ' ').trim().toLowerCase();
}

function ceraCanonConsoleHeader_(val) {
  const k = ceraNormConsoleKey_(val);
  if (!k) return '';
  const map = CERA_CONSOLE_LABELS && CERA_CONSOLE_LABELS.columns;
  return (map && Object.prototype.hasOwnProperty.call(map, k)) ? map[k] : k;
}

function ceraCanonConsoleEvent_(val) {
  if (val === null || val === undefined || val === '') return '';
  const s = String(val).trim();
  const k = ceraNormConsoleKey_(s);
  const map = CERA_CONSOLE_LABELS && CERA_CONSOLE_LABELS.events;
  return (map && Object.prototype.hasOwnProperty.call(map, k)) ? map[k] : s;
}

function ceraCanonConsoleTrigger_(val) {
  if (val === null || val === undefined || val === '') return '';
  const s = String(val).trim();
  const k = ceraNormConsoleKey_(s);
  const map = CERA_CONSOLE_LABELS && CERA_CONSOLE_LABELS.triggerTypes;
  return (map && Object.prototype.hasOwnProperty.call(map, k)) ? map[k] : s;
}

function ceraCanonConsoleResult_(val) {
  if (val === null || val === undefined || val === '') return '';
  const s = String(val).trim();
  const k = ceraNormConsoleKey_(s);
  const map = CERA_CONSOLE_LABELS && CERA_CONSOLE_LABELS.eventResults;
  return (map && Object.prototype.hasOwnProperty.call(map, k)) ? map[k] : s;
}

function ceraCanonConsoleCategory_(val) {
  if (val === null || val === undefined || val === '') return '';
  const s = String(val).trim();
  const k = ceraNormConsoleKey_(s);
  const map = CERA_CONSOLE_LABELS && CERA_CONSOLE_LABELS.categories;
  return (map && Object.prototype.hasOwnProperty.call(map, k)) ? map[k] : s;
}
