// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using cbcmSchema.BrowserAnnotatedField;
//
//    var browserAnnotatedItem = BrowserAnnotatedItem.FromJson(jsonString);

namespace cbcmSchema.BrowserAnnotatedField
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class BrowserAnnotatedItem
    {
        [JsonProperty("deviceId", NullValueHandling = NullValueHandling.Ignore)]
        public string DeviceId { get; set; }

        [JsonProperty("annotatedUser", NullValueHandling = NullValueHandling.Ignore)]
        public string AnnotatedUser { get; set; }

        [JsonProperty("annotatedLocation", NullValueHandling = NullValueHandling.Ignore)]
        public string AnnotatedLocation { get; set; }

        [JsonProperty("annotatedNotes", NullValueHandling = NullValueHandling.Ignore)]
        public string AnnotatedNotes { get; set; }

        [JsonProperty("annotatedAssetId", NullValueHandling = NullValueHandling.Ignore)]
        public string AnnotatedAssetId { get; set; }
    }

    public partial class BrowserAnnotatedItem
    {
        public static BrowserAnnotatedItem FromJson(string json) => JsonConvert.DeserializeObject<BrowserAnnotatedItem>(json, cbcmSchema.BrowserAnnotatedField.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this BrowserAnnotatedItem self) => JsonConvert.SerializeObject(self, cbcmSchema.BrowserAnnotatedField.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
