/**
 * @file Interactive setup CLI for Pocket CEP.
 *
 * Run with: npm run setup
 *
 * Guides a new developer through the .env.local configuration with live
 * validation at every step. Prompts are mode-aware (user_oauth asks for
 * Google OAuth creds; service_account walks through ADC) and API keys
 * are probed against the real upstream service before the script moves
 * on — so "setup finishes clean" is a real guarantee, not a vibe.
 *
 * Safe to re-run: existing .env.local values are loaded as defaults and
 * any keys we don't recognise are preserved unchanged on write.
 *
 * The CLI uses `@clack/prompts` for the modern boxed/connected step
 * style (the same prompt library Astro, Solid, Bun, and Drizzle use).
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { randomBytes } from "node:crypto";
import { spawnSync } from "node:child_process";

import * as p from "@clack/prompts";

import {
  probeAnthropicKey,
  probeGeminiKey,
  probeMcpServer,
} from "../src/lib/doctor-checks";
import { DEFAULT_MCP_URL } from "../src/lib/constants";
import { getErrorMessage } from "../src/lib/errors";
import { inferLlmProvider, type EnvMap } from "./setup-helpers";

const ENV_PATH = resolve(process.cwd(), ".env.local");

/**
 * Wraps every clack prompt so cancellation (Ctrl-C, ESC) terminates
 * the script cleanly. Without this, clack returns a Symbol that would
 * silently flow into downstream logic.
 */
async function ask<T>(promise: Promise<T | symbol>): Promise<T> {
  const value = await promise;
  if (p.isCancel(value)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }
  return value as T;
}

/**
 * Parses an existing .env.local into a map so we can preserve unknown
 * keys and pre-fill known ones as prompt defaults. Mirrors the trivial
 * parser used by doctor.ts — no quoting, no variable expansion.
 */
function readExistingEnv(): EnvMap {
  if (!existsSync(ENV_PATH)) return {};
  const content = readFileSync(ENV_PATH, "utf-8");
  const env: EnvMap = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    env[key] = value;
  }
  return env;
}

/**
 * Writes the env map back to disk as a predictable, human-editable file:
 * a header, then `KEY=value` lines grouped by section. Any keys in the
 * map we don't have a category for land under "Other" so re-running
 * setup never drops user additions on the floor.
 */
function writeEnv(env: EnvMap): void {
  const ordered: Array<[string, string[]]> = [
    [
      "Secrets",
      [
        "BETTER_AUTH_SECRET",
        "GOOGLE_AI_API_KEY",
        "ANTHROPIC_API_KEY",
        "CEP_SERVICE_ACCOUNT_KEY_JSON",
      ],
    ],
    ["Google OAuth (user_oauth mode only)", ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"]],
    ["Mode", ["AUTH_MODE", "LLM_PROVIDER", "LLM_MODEL"]],
    ["URLs", ["BETTER_AUTH_URL", "MCP_SERVER_URL"]],
  ];

  const seen = new Set<string>();
  const lines: string[] = [
    "# Pocket CEP — .env.local (gitignored). Generated by `npm run setup`.",
    "# Holds your secrets and any per-developer overrides; wins over the",
    "# committed `.env` for any key set here. Re-running setup preserves",
    "# the values you set; hand-edits are safe.",
    "",
  ];

  for (const [section, keys] of ordered) {
    const present = keys.filter((k) => env[k] !== undefined && env[k] !== "");
    if (present.length === 0) continue;
    lines.push(`# ${section}`);
    for (const key of present) {
      lines.push(`${key}=${env[key]}`);
      seen.add(key);
    }
    lines.push("");
  }

  const unknown = Object.keys(env).filter((k) => !seen.has(k) && env[k] !== "");
  if (unknown.length > 0) {
    lines.push("# Other");
    for (const key of unknown) {
      lines.push(`${key}=${env[key]}`);
    }
    lines.push("");
  }

  writeFileSync(ENV_PATH, lines.join("\n"), { mode: 0o600 });
}

/**
 * Step 1: auth mode. We explain both flavors inline and use the
 * existing .env.local value as the default if re-running setup.
 */
async function chooseAuthMode(current: string | undefined) {
  p.log.step("Step 1/6 · Authentication mode");
  return ask<"service_account" | "user_oauth">(
    p.select({
      message: "How does Pocket CEP talk to Google APIs?",
      initialValue: current === "user_oauth" ? "user_oauth" : "service_account",
      options: [
        {
          label: "Service account (recommended for local demos)",
          value: "service_account",
          hint: "Uses `gcloud auth application-default login`. No user sign-in; shared identity.",
        },
        {
          label: "User OAuth (per-user attribution)",
          value: "user_oauth",
          hint: "Users sign in with Google. Their token is forwarded to the MCP server.",
        },
      ],
    }),
  );
}

const SECRET_PLACEHOLDER = "please-change-me-to-a-real-secret";

/**
 * Step 2: BETTER_AUTH_SECRET. Comes right after auth mode so the auth
 * setup stays grouped (the LLM provider+key pair flows next as a
 * single unit). If the current value looks unsafe (missing or the
 * placeholder from .env.local.example), we offer to generate a fresh
 * one. Otherwise we leave it untouched.
 */
async function chooseAuthSecret(current: string | undefined): Promise<string> {
  p.log.step("Step 2/6 · BetterAuth signing secret");

  const hasReal = current && current !== SECRET_PLACEHOLDER && current.length >= 32;
  if (hasReal) {
    const keep = await ask(
      p.confirm({
        message: "An existing BETTER_AUTH_SECRET looks valid. Keep it?",
        initialValue: true,
      }),
    );
    if (keep) return current;
  }

  const generate = await ask(
    p.confirm({
      message: "Generate a cryptographically random 32-byte secret now?",
      initialValue: true,
    }),
  );
  if (generate) {
    const secret = randomBytes(32).toString("base64");
    p.log.success("Generated a fresh 32-byte secret.");
    return secret;
  }

  return ask(
    p.password({
      message: "Paste your own BETTER_AUTH_SECRET",
      validate: (v) => (v && v.trim().length >= 16 ? undefined : "Use at least 16 characters"),
    }),
  );
}

/**
 * Step 3: LLM provider. Validation happens on the API-key step
 * downstream — we only pick the provider here. The default is
 * inferred from `.env.local` (explicit `LLM_PROVIDER` first, then
 * which API key happens to be set) so re-running setup with an
 * already-pasted key pre-selects the matching provider instead of
 * always landing on Claude.
 */
async function chooseLlmProvider(existing: EnvMap) {
  p.log.step("Step 3/6 · LLM provider");
  const inferred = inferLlmProvider(existing);
  if (inferred.reason) p.log.info(inferred.reason);
  return ask<"claude" | "gemini">(
    p.select({
      message: "Which model powers the chat agent?",
      initialValue: inferred.value,
      options: [
        {
          label: "Google Gemini",
          value: "gemini",
          hint: "via @ai-sdk/google — needs GOOGLE_AI_API_KEY (aistudio.google.com/apikey)",
        },
        {
          label: "Anthropic Claude",
          value: "claude",
          hint: "via @ai-sdk/anthropic — needs ANTHROPIC_API_KEY (console.anthropic.com)",
        },
      ],
    }),
  );
}

/**
 * If an existing key is present, probe it first and offer to keep it
 * so we don't ask the user to re-paste a working secret. Returns the
 * kept value or `null` to signal "prompt for a new one".
 */
async function tryKeepExistingKey(
  label: string,
  current: string | undefined,
  probe: (value: string) => Promise<{ ok: boolean; message: string }>,
): Promise<string | null> {
  if (!current) return null;
  const s = p.spinner();
  s.start(`Probing existing ${label}`);
  const result = await probe(current);
  if (!result.ok) {
    s.stop(`Existing ${label} was rejected — paste a new one`);
    return null;
  }
  s.stop(`Existing ${label} works`);
  const keep = await ask(
    p.confirm({ message: `Keep the existing ${label}?`, initialValue: true }),
  );
  return keep ? current : null;
}

/**
 * Step 4 (claude): Anthropic key — masked input, validated by the
 * same /v1/messages probe doctor uses. If the key is wrong we
 * re-prompt; we never move on with a bad key.
 */
async function promptAnthropicKey(current: string | undefined) {
  p.log.step("Step 4/6 · ANTHROPIC_API_KEY");
  p.log.info("We'll probe api.anthropic.com to confirm the key works.");

  const kept = await tryKeepExistingKey("Anthropic key", current, probeAnthropicKey);
  if (kept) return kept;

  // clack's `validate` is synchronous (returns string | Error | undefined),
  // so the API probe runs in a loop after the prompt. The prompt itself
  // only does the cheap format check.
  for (;;) {
    const key = await ask(
      p.password({
        message: "Paste your Anthropic API key (console.anthropic.com → Settings → API Keys)",
        validate: (value) => {
          if (!value) return "Key is required";
          const trimmed = value.trim();
          if (!trimmed) return "Key is required";
          if (!trimmed.startsWith("sk-ant-")) {
            return "Anthropic keys start with `sk-ant-` — double-check the value";
          }
          return undefined;
        },
      }),
    );
    const trimmed = key.trim();
    const s = p.spinner();
    s.start("Probing key against api.anthropic.com");
    const probe = await probeAnthropicKey(trimmed);
    if (probe.ok) {
      s.stop("Key accepted");
      return trimmed;
    }
    s.stop(`Key rejected — ${probe.message}`);
  }
}

/**
 * Step 4 (gemini): Google AI key — validated by listing models on
 * generativelanguage.googleapis.com.
 */
async function promptGeminiKey(current: string | undefined) {
  p.log.step("Step 4/6 · GOOGLE_AI_API_KEY");
  p.log.info("We'll probe generativelanguage.googleapis.com to confirm the key works.");

  const kept = await tryKeepExistingKey("Google AI key", current, probeGeminiKey);
  if (kept) return kept;

  for (;;) {
    const key = await ask(
      p.password({
        message: "Paste your Google AI API key (aistudio.google.com/apikey)",
        validate: (value) => {
          if (!value || !value.trim()) return "Key is required";
          return undefined;
        },
      }),
    );
    const trimmed = key.trim();
    const s = p.spinner();
    s.start("Probing key against generativelanguage.googleapis.com");
    const probe = await probeGeminiKey(trimmed);
    if (probe.ok) {
      s.stop("Key accepted");
      return trimmed;
    }
    s.stop(`Key rejected — ${probe.message}`);
  }
}

const GOOGLE_CLIENT_ID_RE = /^\d+-\w+\.apps\.googleusercontent\.com$/;

/**
 * Step 5 (user_oauth mode): Google OAuth client credentials. The
 * client ID format is strict, so we validate it with the same regex
 * the Zod env schema uses — catches paste errors here rather than as
 * a cryptic OAuth error at runtime. Mutually exclusive with the
 * service_account-mode `walkAdcSetup` below — the user only ever
 * sees one of them per setup run.
 */
async function promptGoogleOAuth(current: EnvMap) {
  p.log.step("Step 5/6 · Google OAuth client");
  p.note(
    "Visit console.cloud.google.com → APIs & Services → Credentials.\n" +
      "Add this redirect URI to your OAuth client:\n" +
      "  http://localhost:3000/api/auth/callback/google",
    "OAuth client setup",
  );

  const clientId = await ask(
    p.text({
      message: "GOOGLE_CLIENT_ID",
      defaultValue: current.GOOGLE_CLIENT_ID || undefined,
      validate: (v) => {
        if (!v) return "Client ID is required";
        const trimmed = v.trim();
        if (!trimmed) return "Client ID is required";
        return GOOGLE_CLIENT_ID_RE.test(trimmed)
          ? undefined
          : "Expected format: 123456789-abc.apps.googleusercontent.com";
      },
    }),
  );

  const clientSecret = await ask(
    p.password({
      message: "GOOGLE_CLIENT_SECRET",
      validate: (v) => (v && v.trim().length > 0 ? undefined : "Client secret is required"),
    }),
  );

  return { clientId: clientId.trim(), clientSecret: clientSecret.trim() };
}



/**
 * Step 5 (service_account mode): prompts the user to configure a Service
 * Account JSON key. If they provide one, we validate it and write it to
 * .env.local as CEP_SERVICE_ACCOUNT_KEY_JSON.
 */
async function walkServiceAccountSetup(): Promise<string | undefined> {
  p.log.step("Step 5/6 · Service Account Key");

  const hasKey = await ask(
    p.confirm({
      message: "Do you have a Service Account JSON key file? (Recommended for service_account mode)",
      initialValue: true,
    }),
  );

  if (!hasKey) {
    p.log.warn(
      "Service Account mode requires a key file to function.\n" +
        "You will need to manually set CEP_SERVICE_ACCOUNT_KEY_JSON in .env.local later.",
    );
    return undefined;
  }

  for (;;) {
    const keyPath = await ask(
      p.text({
        message: "Path to Service Account JSON key file",
        placeholder: "/path/to/key.json",
        validate: (value) => {
          if (!value) return "Path is required";
          const trimmed = value.trim();
          if (!trimmed) return "Path is required";
          return undefined;
        },
      }),
    );

    const resolvedPath = resolve(process.cwd(), keyPath.trim());
    if (!existsSync(resolvedPath)) {
      p.log.error(`File not found: ${resolvedPath}`);
      const next = await retryOrSkipPrompt();
      if (next === "skip") return undefined;
      continue;
    }

    try {
      const content = readFileSync(resolvedPath, "utf-8");
      const json = JSON.parse(content);
      if (json.type !== "service_account") {
        p.log.error("JSON file is not a Service Account key (missing type: 'service_account')");
        const next = await retryOrSkipPrompt();
        if (next === "skip") return undefined;
        continue;
      }

      // Minify and return
      const minified = JSON.stringify(json);
      p.log.success("Service Account key loaded and validated.");
      return minified;
    } catch (e) {
      p.log.error(`Failed to parse JSON: ${getErrorMessage(e)}`);
      const next = await retryOrSkipPrompt();
      if (next === "skip") return undefined;
    }
  }
}

async function retryOrSkipPrompt(): Promise<"retry" | "skip"> {
  return ask<"retry" | "skip">(
    p.select({
      message: "What next?",
      initialValue: "retry",
      options: [
        { label: "Try a different path", value: "retry" },
        { label: "Skip for now", value: "skip" },
      ],
    }),
  );
}

/**
 * Step 6: MCP server URL. The localhost default is opaque without
 * context — this step explains that the MCP server is a separate
 * process (the published `@google/chrome-enterprise-premium-mcp`
 * package, or a local clone if you're hacking on it) before asking
 * the URL question. A custom-URL escape hatch covers remote
 * deployments.
 */
async function chooseMcpUrl(current: string | undefined): Promise<string> {
  p.log.step("Step 6/6 · MCP server");
  p.note(
    "The CEP admin tools live in a separate process; Pocket CEP\n" +
      "talks to it over HTTP.\n\n" +
      "Most contributors use the official npm package, which\n" +
      "`npm run dev:full` launches alongside Next on port 4000:\n\n" +
      "  npx --prefer-online @google/chrome-enterprise-premium-mcp\n\n" +
      "If `npx` doesn't work on your network, or you've cloned the\n" +
      "MCP source locally, set MCP_SERVER_CMD in .env.local — both\n" +
      "`npm run dev:full` and `npm run doctor` honour it:\n\n" +
      '  MCP_SERVER_CMD="node /path/to/cmcp/mcp-server.js"\n\n' +
      `Either way, Pocket CEP still dials ${DEFAULT_MCP_URL} —\n` +
      "the URL doesn't change; only what's on the other end does.",
    "About the MCP server",
  );

  const isCustom = current !== undefined && current !== "" && current !== DEFAULT_MCP_URL;

  const choice = await ask<"local" | "custom">(
    p.select({
      message: "Which URL should Pocket CEP dial?",
      initialValue: isCustom ? "custom" : "local",
      options: [
        {
          label: `${DEFAULT_MCP_URL} — local, started by \`npm run dev:full\``,
          value: "local",
          hint: "Covers both the npm package and a local source clone (via MCP_SERVER_CMD).",
        },
        {
          label: "Somewhere else — I have an MCP server running remotely",
          value: "custom",
          hint: "Enter a URL (staging deployment, Cloud Run, shared demo, etc.).",
        },
      ],
    }),
  );

  if (choice === "local") {
    p.log.info(`Set to ${DEFAULT_MCP_URL}. Start the server with \`npm run dev:full\` when ready.`);
    return DEFAULT_MCP_URL;
  }

  // Sync validate handles format; reachability is probed in a loop
  // after the prompt (clack's validate signature is synchronous).
  for (;;) {
    const url = await ask(
      p.text({
        message: "MCP_SERVER_URL",
        defaultValue: isCustom ? current : DEFAULT_MCP_URL,
        validate: (value) => {
          if (!value) return "URL is required";
          const trimmed = value.trim();
          if (!trimmed) return "URL is required";
          try {
            new URL(trimmed);
          } catch {
            return "Not a valid URL";
          }
          return undefined;
        },
      }),
    );
    const trimmed = url.trim();
    const s = p.spinner();
    s.start(`Probing ${trimmed}`);
    const result = await probeMcpServer(trimmed);
    if (result.ok) {
      s.stop(`MCP server reachable at ${trimmed}`);
      return trimmed;
    }
    s.stop(`Not reachable — ${result.message}`);
    const next = await ask<"retry" | "skip">(
      p.select({
        message: "What next?",
        initialValue: "retry",
        options: [
          { label: "Try a different URL", value: "retry" },
          {
            label: "Use this URL anyway",
            value: "skip",
            hint: "Use when the server isn't running yet but you know the URL is right.",
          },
        ],
      }),
    );
    if (next === "skip") return trimmed;
  }
}

async function optionalModelOverride(
  provider: "claude" | "gemini",
  current: string | undefined,
): Promise<string> {
  const wantOverride = await ask(
    p.confirm({
      message: `Use the default ${provider} model? (No lets you pin a specific model ID.)`,
      initialValue: !current,
    }),
  );
  if (wantOverride) return "";
  return ask(
    p.text({
      message: `LLM_MODEL for ${provider}`,
      defaultValue: current,
      validate: (v) => (v && v.trim().length > 0 ? undefined : "Leave blank to use the default"),
    }),
  );
}

async function main() {
  p.intro("Pocket CEP — Interactive Setup");
  p.log.message("Configures .env.local. Existing values are used as defaults.");

  const existing = readExistingEnv();

  const authMode = await chooseAuthMode(existing.AUTH_MODE);
  const authSecret = await chooseAuthSecret(existing.BETTER_AUTH_SECRET);
  const llmProvider = await chooseLlmProvider(existing);

  const apiKey =
    llmProvider === "claude"
      ? await promptAnthropicKey(existing.ANTHROPIC_API_KEY)
      : await promptGeminiKey(existing.GOOGLE_AI_API_KEY);

  p.note(
    "The in-app top-bar model picker accepts keys for any provider —\n" +
      "Claude, Gemini, OpenAI — for casual use. Keys live in your\n" +
      "browser's localStorage only, no need to re-run setup.",
    "Tip: BYOK in the app",
  );

  let clientId = "";
  let clientSecret = "";
  let saKeyJson = "";
  if (authMode === "user_oauth") {
    const creds = await promptGoogleOAuth(existing);
    clientId = creds.clientId;
    clientSecret = creds.clientSecret;
  } else {
    const key = await walkServiceAccountSetup();
    if (key) saKeyJson = key;
  }

  const mcpUrl = await chooseMcpUrl(existing.MCP_SERVER_URL);
  const modelOverride = await optionalModelOverride(llmProvider, existing.LLM_MODEL);

  const merged: EnvMap = {
    ...existing,
    AUTH_MODE: authMode,
    LLM_PROVIDER: llmProvider,
    BETTER_AUTH_SECRET: authSecret,
    MCP_SERVER_URL: mcpUrl,
    LLM_MODEL: modelOverride,
  };

  if (saKeyJson) {
    merged.CEP_SERVICE_ACCOUNT_KEY_JSON = saKeyJson;
  }

  // Only set the chosen provider's key; leave any previously-set keys
  // for the other provider(s) intact. The Zod schema discriminates on
  // LLM_PROVIDER and only requires the matching key — extras are
  // allowed, and the in-app model picker can use them as BYOK.
  if (llmProvider === "claude") {
    merged.ANTHROPIC_API_KEY = apiKey;
  } else {
    merged.GOOGLE_AI_API_KEY = apiKey;
  }

  if (authMode === "user_oauth") {
    merged.GOOGLE_CLIENT_ID = clientId;
    merged.GOOGLE_CLIENT_SECRET = clientSecret;
  }

  p.note(
    `AUTH_MODE       ${authMode}\n` +
      `LLM_PROVIDER    ${llmProvider}\n` +
      `LLM_MODEL       ${modelOverride || `(default for ${llmProvider})`}\n` +
      `MCP_SERVER_URL  ${mcpUrl}\n` +
      `Secrets         masked, written to .env.local`,
    "Review",
  );

  const write = await ask(
    p.confirm({ message: `Write ${ENV_PATH}?`, initialValue: true }),
  );
  if (!write) {
    p.cancel("Aborted. No files changed.");
    process.exit(0);
  }

  writeEnv(merged);
  p.log.success(`Wrote ${ENV_PATH}`);

  const runDoctor = await ask(
    p.confirm({ message: "Run `npm run doctor` now?", initialValue: true }),
  );
  if (runDoctor) {
    p.outro("Running doctor…");
    spawnSync("npm", ["run", "doctor"], { stdio: "inherit" });
  } else {
    p.outro("Setup complete. Run `npm run doctor` any time to verify.");
  }
}

main().catch((error: unknown) => {
  p.cancel(error instanceof Error ? `Setup failed: ${error.message}` : "Setup failed");
  process.exit(1);
});
