/**
 * @file Interactive setup CLI for Pocket CEP.
 *
 * Run with: npm run setup
 *
 * Guides a new developer through the .env.local configuration with live
 * validation at every step. Prompts are mode-aware (user_oauth asks for
 * Google OAuth creds; service_account walks through ADC) and API keys
 * are probed against the real upstream service before the script moves
 * on — so "setup finishes clean" is a real guarantee, not a vibe.
 *
 * Safe to re-run: existing .env.local values are loaded as defaults and
 * any keys we don't recognise are preserved unchanged on write.
 *
 * The CLI uses `@clack/prompts` for the modern boxed/connected step
 * style (the same prompt library Astro, Solid, Bun, and Drizzle use).
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import { randomBytes } from "node:crypto";
import { spawnSync } from "node:child_process";

import * as p from "@clack/prompts";

import {
  probeAdcToken,
  probeAnthropicKey,
  probeGeminiKey,
  probeMcpServer,
} from "../src/lib/doctor-checks";
import { formatGcloudLoginCommand } from "../src/lib/google-scopes";
import { DEFAULT_MCP_URL } from "../src/lib/constants";
import { inferLlmProvider, type EnvMap } from "./setup-helpers";

const ENV_PATH = resolve(process.cwd(), ".env.local");

/**
 * Wraps every clack prompt so cancellation (Ctrl-C, ESC) terminates
 * the script cleanly. Without this, clack returns a Symbol that would
 * silently flow into downstream logic.
 */
async function ask<T>(promise: Promise<T | symbol>): Promise<T> {
  const value = await promise;
  if (p.isCancel(value)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }
  return value as T;
}

/**
 * Parses an existing .env.local into a map so we can preserve unknown
 * keys and pre-fill known ones as prompt defaults. Mirrors the trivial
 * parser used by doctor.ts — no quoting, no variable expansion.
 */
function readExistingEnv(): EnvMap {
  if (!existsSync(ENV_PATH)) return {};
  const content = readFileSync(ENV_PATH, "utf-8");
  const env: EnvMap = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    env[key] = value;
  }
  return env;
}

/**
 * Writes the env map back to disk as a predictable, human-editable file:
 * a header, then `KEY=value` lines grouped by section. Any keys in the
 * map we don't have a category for land under "Other" so re-running
 * setup never drops user additions on the floor.
 */
function writeEnv(env: EnvMap): void {
  const ordered: Array<[string, string[]]> = [
    ["Secrets", ["BETTER_AUTH_SECRET", "ANTHROPIC_API_KEY", "GOOGLE_AI_API_KEY"]],
    ["Google OAuth (user_oauth mode only)", ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"]],
    ["Mode", ["AUTH_MODE", "LLM_PROVIDER", "LLM_MODEL"]],
    ["URLs", ["BETTER_AUTH_URL", "MCP_SERVER_URL"]],
  ];

  const seen = new Set<string>();
  const lines: string[] = [
    "# Pocket CEP — .env.local (gitignored). Generated by `npm run setup`.",
    "# Holds your secrets and any per-developer overrides; wins over the",
    "# committed `.env` for any key set here. Re-running setup preserves",
    "# the values you set; hand-edits are safe.",
    "",
  ];

  for (const [section, keys] of ordered) {
    const present = keys.filter((k) => env[k] !== undefined && env[k] !== "");
    if (present.length === 0) continue;
    lines.push(`# ${section}`);
    for (const key of present) {
      lines.push(`${key}=${env[key]}`);
      seen.add(key);
    }
    lines.push("");
  }

  const unknown = Object.keys(env).filter((k) => !seen.has(k) && env[k] !== "");
  if (unknown.length > 0) {
    lines.push("# Other");
    for (const key of unknown) {
      lines.push(`${key}=${env[key]}`);
    }
    lines.push("");
  }

  writeFileSync(ENV_PATH, lines.join("\n"), { mode: 0o600 });
}

/**
 * Step 1: auth mode. We explain both flavors inline and use the
 * existing .env.local value as the default if re-running setup.
 */
async function chooseAuthMode(current: string | undefined) {
  p.log.step("Step 1/6 · Authentication mode");
  return ask<"service_account" | "user_oauth">(
    p.select({
      message: "How does Pocket CEP talk to Google APIs?",
      initialValue: current === "user_oauth" ? "user_oauth" : "service_account",
      options: [
        {
          label: "Service account (recommended for local demos)",
          value: "service_account",
          hint: "Uses `gcloud auth application-default login`. No user sign-in; shared identity.",
        },
        {
          label: "User OAuth (per-user attribution)",
          value: "user_oauth",
          hint: "Users sign in with Google. Their token is forwarded to the MCP server.",
        },
      ],
    }),
  );
}

const SECRET_PLACEHOLDER = "please-change-me-to-a-real-secret";

/**
 * Step 2: BETTER_AUTH_SECRET. Comes right after auth mode so the auth
 * setup stays grouped (the LLM provider+key pair flows next as a
 * single unit). If the current value looks unsafe (missing or the
 * placeholder from .env.local.example), we offer to generate a fresh
 * one. Otherwise we leave it untouched.
 */
async function chooseAuthSecret(current: string | undefined): Promise<string> {
  p.log.step("Step 2/6 · BetterAuth signing secret");

  const hasReal = current && current !== SECRET_PLACEHOLDER && current.length >= 32;
  if (hasReal) {
    const keep = await ask(
      p.confirm({
        message: "An existing BETTER_AUTH_SECRET looks valid. Keep it?",
        initialValue: true,
      }),
    );
    if (keep) return current;
  }

  const generate = await ask(
    p.confirm({
      message: "Generate a cryptographically random 32-byte secret now?",
      initialValue: true,
    }),
  );
  if (generate) {
    const secret = randomBytes(32).toString("base64");
    p.log.success("Generated a fresh 32-byte secret.");
    return secret;
  }

  return ask(
    p.password({
      message: "Paste your own BETTER_AUTH_SECRET",
      validate: (v) => (v && v.trim().length >= 16 ? undefined : "Use at least 16 characters"),
    }),
  );
}

/**
 * Step 3: LLM provider. Validation happens on the API-key step
 * downstream — we only pick the provider here. The default is
 * inferred from `.env.local` (explicit `LLM_PROVIDER` first, then
 * which API key happens to be set) so re-running setup with an
 * already-pasted key pre-selects the matching provider instead of
 * always landing on Claude.
 */
async function chooseLlmProvider(existing: EnvMap) {
  p.log.step("Step 3/6 · LLM provider");
  const inferred = inferLlmProvider(existing);
  if (inferred.reason) p.log.info(inferred.reason);
  return ask<"claude" | "gemini">(
    p.select({
      message: "Which model powers the chat agent?",
      initialValue: inferred.value,
      options: [
        {
          label: "Anthropic Claude",
          value: "claude",
          hint: "via @ai-sdk/anthropic — needs ANTHROPIC_API_KEY (console.anthropic.com)",
        },
        {
          label: "Google Gemini",
          value: "gemini",
          hint: "via @ai-sdk/google — needs GOOGLE_AI_API_KEY (aistudio.google.com/apikey)",
        },
      ],
    }),
  );
}

/**
 * If an existing key is present, probe it first and offer to keep it
 * so we don't ask the user to re-paste a working secret. Returns the
 * kept value or `null` to signal "prompt for a new one".
 */
async function tryKeepExistingKey(
  label: string,
  current: string | undefined,
  probe: (value: string) => Promise<{ ok: boolean; message: string }>,
): Promise<string | null> {
  if (!current) return null;
  const s = p.spinner();
  s.start(`Probing existing ${label}`);
  const result = await probe(current);
  if (!result.ok) {
    s.stop(`Existing ${label} was rejected — paste a new one`);
    return null;
  }
  s.stop(`Existing ${label} works`);
  const keep = await ask(
    p.confirm({ message: `Keep the existing ${label}?`, initialValue: true }),
  );
  return keep ? current : null;
}

/**
 * Step 4 (claude): Anthropic key — masked input, validated by the
 * same /v1/messages probe doctor uses. If the key is wrong we
 * re-prompt; we never move on with a bad key.
 */
async function promptAnthropicKey(current: string | undefined) {
  p.log.step("Step 4/6 · ANTHROPIC_API_KEY");
  p.log.info("We'll probe api.anthropic.com to confirm the key works.");

  const kept = await tryKeepExistingKey("Anthropic key", current, probeAnthropicKey);
  if (kept) return kept;

  // clack's `validate` is synchronous (returns string | Error | undefined),
  // so the API probe runs in a loop after the prompt. The prompt itself
  // only does the cheap format check.
  for (;;) {
    const key = await ask(
      p.password({
        message: "Paste your Anthropic API key (console.anthropic.com → Settings → API Keys)",
        validate: (value) => {
          if (!value) return "Key is required";
          const trimmed = value.trim();
          if (!trimmed) return "Key is required";
          if (!trimmed.startsWith("sk-ant-")) {
            return "Anthropic keys start with `sk-ant-` — double-check the value";
          }
          return undefined;
        },
      }),
    );
    const trimmed = key.trim();
    const s = p.spinner();
    s.start("Probing key against api.anthropic.com");
    const probe = await probeAnthropicKey(trimmed);
    if (probe.ok) {
      s.stop("Key accepted");
      return trimmed;
    }
    s.stop(`Key rejected — ${probe.message}`);
  }
}

/**
 * Step 4 (gemini): Google AI key — validated by listing models on
 * generativelanguage.googleapis.com.
 */
async function promptGeminiKey(current: string | undefined) {
  p.log.step("Step 4/6 · GOOGLE_AI_API_KEY");
  p.log.info("We'll probe generativelanguage.googleapis.com to confirm the key works.");

  const kept = await tryKeepExistingKey("Google AI key", current, probeGeminiKey);
  if (kept) return kept;

  for (;;) {
    const key = await ask(
      p.password({
        message: "Paste your Google AI API key (aistudio.google.com/apikey)",
        validate: (value) => {
          if (!value || !value.trim()) return "Key is required";
          return undefined;
        },
      }),
    );
    const trimmed = key.trim();
    const s = p.spinner();
    s.start("Probing key against generativelanguage.googleapis.com");
    const probe = await probeGeminiKey(trimmed);
    if (probe.ok) {
      s.stop("Key accepted");
      return trimmed;
    }
    s.stop(`Key rejected — ${probe.message}`);
  }
}

const GOOGLE_CLIENT_ID_RE = /^\d+-\w+\.apps\.googleusercontent\.com$/;

/**
 * Step 5 (user_oauth mode): Google OAuth client credentials. The
 * client ID format is strict, so we validate it with the same regex
 * the Zod env schema uses — catches paste errors here rather than as
 * a cryptic OAuth error at runtime. Mutually exclusive with the
 * service_account-mode `walkAdcSetup` below — the user only ever
 * sees one of them per setup run.
 */
async function promptGoogleOAuth(current: EnvMap) {
  p.log.step("Step 5/6 · Google OAuth client");
  p.note(
    "Visit console.cloud.google.com → APIs & Services → Credentials.\n" +
      "Add this redirect URI to your OAuth client:\n" +
      "  http://localhost:3000/api/auth/callback/google",
    "OAuth client setup",
  );

  const clientId = await ask(
    p.text({
      message: "GOOGLE_CLIENT_ID",
      defaultValue: current.GOOGLE_CLIENT_ID || undefined,
      validate: (v) => {
        if (!v) return "Client ID is required";
        const trimmed = v.trim();
        if (!trimmed) return "Client ID is required";
        return GOOGLE_CLIENT_ID_RE.test(trimmed)
          ? undefined
          : "Expected format: 123456789-abc.apps.googleusercontent.com";
      },
    }),
  );

  const clientSecret = await ask(
    p.password({
      message: "GOOGLE_CLIENT_SECRET",
      validate: (v) => (v && v.trim().length > 0 ? undefined : "Client secret is required"),
    }),
  );

  return { clientId: clientId.trim(), clientSecret: clientSecret.trim() };
}

/**
 * Returns true if the `gcloud` CLI is on PATH. ADC depends on it, so
 * we preflight before the ADC probe to give a clearer error when it's
 * missing entirely (the probe's "no credentials" message is confusing
 * if the real cause is "gcloud isn't installed yet").
 */
function isGcloudInstalled(): boolean {
  return spawnSync("gcloud", ["--version"], { stdio: "ignore" }).status === 0;
}

/**
 * Returns the platform-appropriate install hint as one block of text
 * suitable for `p.note()`. Extracted so both the "not installed" and
 * "still not installed after re-check" branches render the same
 * guidance.
 */
function gcloudInstallHints(): string {
  let install: string;
  if (process.platform === "darwin") {
    install =
      "  brew install --cask google-cloud-sdk\n" +
      "  or see https://cloud.google.com/sdk/docs/install-sdk";
  } else if (process.platform === "linux") {
    install = "  https://cloud.google.com/sdk/docs/install-sdk#linux";
  } else if (process.platform === "win32") {
    install = "  https://cloud.google.com/sdk/docs/install-sdk#windows";
  } else {
    install = "  https://cloud.google.com/sdk/docs/install-sdk";
  }
  return (
    "The Google Cloud CLI is required for service-account mode —\n" +
    "Pocket CEP uses your Application Default Credentials.\n\n" +
    install +
    "\n\nTip: open a new shell after installing so PATH updates take effect."
  );
}

/**
 * Loops on "re-check or skip" until gcloud is installed or the user
 * chooses to defer. Returns true when gcloud is ready, false when the
 * user opted to skip ADC entirely.
 */
async function ensureGcloudInstalled(): Promise<boolean> {
  const s = p.spinner();
  s.start("Checking for `gcloud`");
  if (isGcloudInstalled()) {
    s.stop("`gcloud` is installed");
    return true;
  }
  s.stop("`gcloud` is not installed");

  for (;;) {
    p.note(gcloudInstallHints(), "Install gcloud");
    const next = await ask<"recheck" | "skip">(
      p.select({
        message: "When you're ready:",
        initialValue: "recheck",
        options: [
          {
            label: "I've installed gcloud — re-check now",
            value: "recheck",
            hint: "Verifies `gcloud --version` succeeds, then continues with ADC.",
          },
          {
            label: "Skip ADC for now",
            value: "skip",
            hint: "Finish writing .env.local; run `npm run doctor` to verify later.",
          },
        ],
      }),
    );

    if (next === "skip") {
      p.note(
        "Once gcloud is installed:\n" +
          "  gcloud auth application-default login\n" +
          "  npm run doctor",
        "Skipping ADC",
      );
      return false;
    }

    const recheck = p.spinner();
    recheck.start("Re-checking for `gcloud`");
    if (isGcloudInstalled()) {
      recheck.stop("`gcloud` is installed");
      return true;
    }
    recheck.stop("Still not found. Open a new shell to refresh PATH.");
  }
}

/**
 * Loops on "re-check or skip" until the ADC token exchange succeeds
 * or the user opts out. Assumes gcloud is already installed. Returns
 * true on a successful login (so the caller can chain quota-project
 * setup) or false on skip.
 */
async function ensureAdcLogin(): Promise<boolean> {
  for (;;) {
    const s = p.spinner();
    s.start("Checking Google ADC");
    const result = await probeAdcToken();
    if (result.ok) {
      s.stop("ADC is configured and working");
      return true;
    }
    s.stop(`ADC not ready — ${result.message}`);

    p.note(
      "Pocket CEP needs a Workspace admin's ADC to call Chrome\n" +
        "Management, Admin SDK Directory + Reports, Cloud Identity,\n" +
        "and Licensing APIs.\n\n" +
        "Run this in another terminal — paste as a single line:\n\n" +
        formatGcloudLoginCommand() +
        "\n\nSetup will help pin a quota project once login succeeds.",
      "ADC login",
    );

    const next = await ask<"recheck" | "skip">(
      p.select({
        message: "When you're ready:",
        initialValue: "recheck",
        options: [
          {
            label: "I've logged in — re-check now",
            value: "recheck",
            hint: "Verifies the token exchange succeeds.",
          },
          {
            label: "Skip for now",
            value: "skip",
            hint: "`npm run doctor` will verify once you've logged in.",
          },
        ],
      }),
    );

    if (next === "skip") {
      p.log.info("Skipping ADC check. Run `npm run doctor` after logging in to verify.");
      return false;
    }
  }
}

/**
 * Reads the quota_project_id from the ADC credentials file directly
 * (uncached, sync) so a quota project freshly written by gcloud is
 * visible immediately. Returns null when the file is missing, the
 * field is absent, or the JSON is malformed.
 */
function readAdcQuotaProject(): string | null {
  try {
    const credPath = join(homedir(), ".config", "gcloud", "application_default_credentials.json");
    if (!existsSync(credPath)) return null;
    const raw: unknown = JSON.parse(readFileSync(credPath, "utf-8"));
    if (raw && typeof raw === "object" && "quota_project_id" in raw) {
      const value = (raw as { quota_project_id?: unknown }).quota_project_id;
      return typeof value === "string" && value.length > 0 ? value : null;
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Returns the project the user already has configured as their gcloud
 * default (`gcloud config get-value project`). Used as the pre-filled
 * answer for the quota-project prompt — covers the 99% case where
 * someone already has a working gcloud config and just wants to pin
 * the same project for ADC. Returns null if the value is `(unset)`,
 * gcloud is missing, or any other failure.
 */
function detectDefaultGcloudProject(): string | null {
  const result = spawnSync("gcloud", ["config", "get-value", "project", "--quiet"], {
    encoding: "utf-8",
  });
  if (result.status !== 0) return null;
  const value = result.stdout.trim();
  if (!value || value === "(unset)") return null;
  return value;
}

/**
 * Project IDs: 6-30 chars, lowercase letters/digits/hyphens, must
 * start with a letter and end with letter/digit. Caught here as a
 * paste-error guard before the gcloud subprocess call.
 */
const PROJECT_ID_RE = /^[a-z][a-z0-9-]{4,28}[a-z0-9]$/;

/**
 * Pins a quota project on the user's ADC credentials. Avoids
 * `gcloud projects list` because organisations frequently have
 * 100K+ projects and listing them all is slow and useless as a
 * picker. Instead we read any existing quota_project_id, fall back
 * to `gcloud config get-value project`, and prompt the user with
 * that as the default. Loops on retry-or-skip if gcloud rejects the
 * ID (wrong project or no access).
 */
async function ensureQuotaProject(): Promise<void> {
  const existing = readAdcQuotaProject();
  if (existing) {
    p.log.success(`ADC quota project already set: ${existing}`);
    return;
  }

  const detected = detectDefaultGcloudProject();
  if (detected) {
    p.log.info(`Your gcloud config has \`project=${detected}\` — pre-filled as the default.`);
  } else {
    p.note(
      "ADC has no quota project pinned yet. Pocket CEP needs one\n" +
        "so Workspace API calls bill and rate-limit against your project.\n\n" +
        "If you don't know the project ID:\n" +
        "  • `gcloud config get-value project` shows your gcloud default\n" +
        "  • Visit https://console.cloud.google.com/projectselector2 —\n" +
        "    find your project, copy the value in the **ID** column\n" +
        "    (not the display name and not the numeric project number).",
      "Pin a quota project",
    );
  }

  // Loop until set-quota-project succeeds or the user opts out.
  // gcloud rejects IDs the user has no access to even when the syntax
  // is valid; the regex can't catch that, so retry-with-a-different-ID
  // is the natural recovery path.
  let suggestedDefault = detected ?? undefined;
  for (;;) {
    const projectId = await ask(
      p.text({
        message: "Project ID for ADC quota",
        defaultValue: suggestedDefault,
        validate: (v) => {
          if (!v) return "Project ID is required";
          const trimmed = v.trim();
          if (!trimmed) return "Project ID is required";
          if (!PROJECT_ID_RE.test(trimmed)) {
            return "Project IDs are 6-30 chars, lowercase letters/digits/hyphens, starting with a letter";
          }
          return undefined;
        },
      }),
    );

    const trimmed = projectId.trim();
    const s = p.spinner();
    s.start(`Setting quota project to ${trimmed}`);
    const set = spawnSync(
      "gcloud",
      ["auth", "application-default", "set-quota-project", trimmed],
      { stdio: "ignore" },
    );
    if (set.status === 0) {
      s.stop(`Quota project set to ${trimmed}`);
      return;
    }
    s.stop(`\`gcloud\` rejected ${trimmed} — wrong ID, or no access?`);

    const next = await ask<"retry" | "skip">(
      p.select({
        message: "What next?",
        initialValue: "retry",
        options: [
          { label: "Try a different project ID", value: "retry" },
          {
            label: "Skip — set it manually later",
            value: "skip",
            hint: "Run `gcloud auth application-default set-quota-project <id>` yourself.",
          },
        ],
      }),
    );

    if (next === "skip") {
      p.log.info(
        "Run manually once you have the right project ID:\n" +
          "  gcloud auth application-default set-quota-project YOUR_PROJECT_ID",
      );
      return;
    }
    suggestedDefault = undefined;
  }
}

/**
 * Step 5 (service_account mode): walks three Google ADC checkpoints
 * with a re-check-or-skip loop at each — install gcloud, log in to
 * ADC, then pin a quota project. The user controls the pace; any
 * step can be skipped and verified later with `npm run doctor`.
 * Mutually exclusive with the user_oauth-mode `promptGoogleOAuth`
 * above.
 */
async function walkAdcSetup() {
  p.log.step("Step 5/6 · Google ADC");
  const gcloudOk = await ensureGcloudInstalled();
  if (!gcloudOk) return;
  const loggedIn = await ensureAdcLogin();
  if (!loggedIn) return;
  await ensureQuotaProject();
}

/**
 * Step 6: MCP server URL. The localhost default is opaque without
 * context — this step explains that the MCP server is a separate
 * process (the published `@google/chrome-enterprise-premium-mcp`
 * package, or a local clone if you're hacking on it) before asking
 * the URL question. A custom-URL escape hatch covers remote
 * deployments.
 */
async function chooseMcpUrl(current: string | undefined): Promise<string> {
  p.log.step("Step 6/6 · MCP server");
  p.note(
    "The CEP admin tools live in a separate process; Pocket CEP\n" +
      "talks to it over HTTP.\n\n" +
      "Most contributors use the official npm package, which\n" +
      "`npm run dev:full` launches alongside Next on port 4000:\n\n" +
      "  npx --prefer-online @google/chrome-enterprise-premium-mcp\n\n" +
      "If `npx` doesn't work on your network, or you've cloned the\n" +
      "MCP source locally, set MCP_SERVER_CMD in .env.local — both\n" +
      "`npm run dev:full` and `npm run doctor` honour it:\n\n" +
      '  MCP_SERVER_CMD="node /path/to/cmcp/mcp-server.js"\n\n' +
      `Either way, Pocket CEP still dials ${DEFAULT_MCP_URL} —\n` +
      "the URL doesn't change; only what's on the other end does.",
    "About the MCP server",
  );

  const isCustom = current !== undefined && current !== "" && current !== DEFAULT_MCP_URL;

  const choice = await ask<"local" | "custom">(
    p.select({
      message: "Which URL should Pocket CEP dial?",
      initialValue: isCustom ? "custom" : "local",
      options: [
        {
          label: `${DEFAULT_MCP_URL} — local, started by \`npm run dev:full\``,
          value: "local",
          hint: "Covers both the npm package and a local source clone (via MCP_SERVER_CMD).",
        },
        {
          label: "Somewhere else — I have an MCP server running remotely",
          value: "custom",
          hint: "Enter a URL (staging deployment, Cloud Run, shared demo, etc.).",
        },
      ],
    }),
  );

  if (choice === "local") {
    p.log.info(`Set to ${DEFAULT_MCP_URL}. Start the server with \`npm run dev:full\` when ready.`);
    return DEFAULT_MCP_URL;
  }

  // Sync validate handles format; reachability is probed in a loop
  // after the prompt (clack's validate signature is synchronous).
  for (;;) {
    const url = await ask(
      p.text({
        message: "MCP_SERVER_URL",
        defaultValue: isCustom ? current : DEFAULT_MCP_URL,
        validate: (value) => {
          if (!value) return "URL is required";
          const trimmed = value.trim();
          if (!trimmed) return "URL is required";
          try {
            new URL(trimmed);
          } catch {
            return "Not a valid URL";
          }
          return undefined;
        },
      }),
    );
    const trimmed = url.trim();
    const s = p.spinner();
    s.start(`Probing ${trimmed}`);
    const result = await probeMcpServer(trimmed);
    if (result.ok) {
      s.stop(`MCP server reachable at ${trimmed}`);
      return trimmed;
    }
    s.stop(`Not reachable — ${result.message}`);
    const next = await ask<"retry" | "skip">(
      p.select({
        message: "What next?",
        initialValue: "retry",
        options: [
          { label: "Try a different URL", value: "retry" },
          {
            label: "Use this URL anyway",
            value: "skip",
            hint: "Use when the server isn't running yet but you know the URL is right.",
          },
        ],
      }),
    );
    if (next === "skip") return trimmed;
  }
}

async function optionalModelOverride(
  provider: "claude" | "gemini",
  current: string | undefined,
): Promise<string> {
  const wantOverride = await ask(
    p.confirm({
      message: `Use the default ${provider} model? (No lets you pin a specific model ID.)`,
      initialValue: !current,
    }),
  );
  if (wantOverride) return "";
  return ask(
    p.text({
      message: `LLM_MODEL for ${provider}`,
      defaultValue: current,
      validate: (v) => (v && v.trim().length > 0 ? undefined : "Leave blank to use the default"),
    }),
  );
}

async function main() {
  p.intro("Pocket CEP — Interactive Setup");
  p.log.message("Configures .env.local. Existing values are used as defaults.");

  const existing = readExistingEnv();

  const authMode = await chooseAuthMode(existing.AUTH_MODE);
  const authSecret = await chooseAuthSecret(existing.BETTER_AUTH_SECRET);
  const llmProvider = await chooseLlmProvider(existing);

  const apiKey =
    llmProvider === "claude"
      ? await promptAnthropicKey(existing.ANTHROPIC_API_KEY)
      : await promptGeminiKey(existing.GOOGLE_AI_API_KEY);

  p.note(
    "The in-app top-bar model picker accepts keys for any provider —\n" +
      "Claude, Gemini, OpenAI — for casual use. Keys live in your\n" +
      "browser's localStorage only, no need to re-run setup.",
    "Tip: BYOK in the app",
  );

  let clientId = "";
  let clientSecret = "";
  if (authMode === "user_oauth") {
    const creds = await promptGoogleOAuth(existing);
    clientId = creds.clientId;
    clientSecret = creds.clientSecret;
  } else {
    await walkAdcSetup();
  }

  const mcpUrl = await chooseMcpUrl(existing.MCP_SERVER_URL);
  const modelOverride = await optionalModelOverride(llmProvider, existing.LLM_MODEL);

  const merged: EnvMap = {
    ...existing,
    AUTH_MODE: authMode,
    LLM_PROVIDER: llmProvider,
    BETTER_AUTH_SECRET: authSecret,
    MCP_SERVER_URL: mcpUrl,
    LLM_MODEL: modelOverride,
  };

  // Only set the chosen provider's key; leave any previously-set keys
  // for the other provider(s) intact. The Zod schema discriminates on
  // LLM_PROVIDER and only requires the matching key — extras are
  // allowed, and the in-app model picker can use them as BYOK.
  if (llmProvider === "claude") {
    merged.ANTHROPIC_API_KEY = apiKey;
  } else {
    merged.GOOGLE_AI_API_KEY = apiKey;
  }

  if (authMode === "user_oauth") {
    merged.GOOGLE_CLIENT_ID = clientId;
    merged.GOOGLE_CLIENT_SECRET = clientSecret;
  }

  p.note(
    `AUTH_MODE       ${authMode}\n` +
      `LLM_PROVIDER    ${llmProvider}\n` +
      `LLM_MODEL       ${modelOverride || `(default for ${llmProvider})`}\n` +
      `MCP_SERVER_URL  ${mcpUrl}\n` +
      `Secrets         masked, written to .env.local`,
    "Review",
  );

  const write = await ask(
    p.confirm({ message: `Write ${ENV_PATH}?`, initialValue: true }),
  );
  if (!write) {
    p.cancel("Aborted. No files changed.");
    process.exit(0);
  }

  writeEnv(merged);
  p.log.success(`Wrote ${ENV_PATH}`);

  const runDoctor = await ask(
    p.confirm({ message: "Run `npm run doctor` now?", initialValue: true }),
  );
  if (runDoctor) {
    p.outro("Running doctor…");
    spawnSync("npm", ["run", "doctor"], { stdio: "inherit" });
  } else {
    p.outro("Setup complete. Run `npm run doctor` any time to verify.");
  }
}

main().catch((error: unknown) => {
  p.cancel(error instanceof Error ? `Setup failed: ${error.message}` : "Setup failed");
  process.exit(1);
});
